In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb

sb.set()

In [2]:
df = pd.read_csv('Dataset.csv', index_col=0)
df.head()

,ADI,Age,person_id,Gender,Subgroup,absence_indicator,analytic_period_id,tenure,overtime,salary,...,extreme_heat_ssp585_2045,wildfire_potential_2018,wildfire_potential_2019,wildfire_potential_2019.1,wildfire_potential_ssp245_2025,wildfire_potential_ssp245_2035,wildfire_potential_ssp245_2045,wildfire_potential_ssp585_2025,wildfire_potential_ssp585_2035,wildfire_potential_ssp585_2045
0,28,37,3030515063,Male,Subgroup P,0,1,18.25,1,115700.0,...,13.380953,10.975000,11.460870,12.070652,6.033403,6.347014,6.512159,6.093082,6.504460,6.743331
1,18,34,9786383567,Male,Subgroup P,0,1,3.99,7,81435.0,...,13.380953,11.141304,11.520652,11.871739,6.033403,6.347014,6.512159,6.093082,6.504460,6.743331
2,15,36,5602306401,Male,Subgroup P,0,1,3.05,1,86400.0,...,15.597403,10.393478,10.777174,11.659783,6.064177,6.380910,6.548825,6.117186,6.522880,6.771772
3,36,41,8107765424,Male,Subgroup P,0,1,20.29,1,79176.0,...,12.290043,11.039130,11.023913,11.963043,6.069724,6.365864,6.512409,6.091926,6.469195,6.700504
4,49,51,7879842771,Male,Subgroup P,0,1,13.66,7,94511.0,...,12.290043,10.760870,11.308696,12.006522,6.069724,6.365864,6.512409,6.091926,6.469195,6.700504

In [3]:
# set gender to 1 and 0

df['Gender'] = np.where(df['Gender'] == 'Male', 1, 0)
df.head()

,ADI,Age,person_id,Gender,Subgroup,absence_indicator,analytic_period_id,tenure,overtime,salary,...,extreme_heat_ssp585_2045,wildfire_potential_2018,wildfire_potential_2019,wildfire_potential_2019.1,wildfire_potential_ssp245_2025,wildfire_potential_ssp245_2035,wildfire_potential_ssp245_2045,wildfire_potential_ssp585_2025,wildfire_potential_ssp585_2035,wildfire_potential_ssp585_2045
0,28,37,3030515063,1,Subgroup P,0,1,18.25,1,115700.0,...,13.380953,10.975000,11.460870,12.070652,6.033403,6.347014,6.512159,6.093082,6.504460,6.743331
1,18,34,9786383567,1,Subgroup P,0,1,3.99,7,81435.0,...,13.380953,11.141304,11.520652,11.871739,6.033403,6.347014,6.512159,6.093082,6.504460,6.743331
2,15,36,5602306401,1,Subgroup P,0,1,3.05,1,86400.0,...,15.597403,10.393478,10.777174,11.659783,6.064177,6.380910,6.548825,6.117186,6.522880,6.771772
3,36,41,8107765424,1,Subgroup P,0,1,20.29,1,79176.0,...,12.290043,11.039130,11.023913,11.963043,6.069724,6.365864,6.512409,6.091926,6.469195,6.700504
4,49,51,7879842771,1,Subgroup P,0,1,13.66,7,94511.0,...,12.290043,10.760870,11.308696,12.006522,6.069724,6.365864,6.512409,6.091926,6.469195,6.700504

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 43184 entries, 0 to 43183
Data columns (total 74 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   ADI                                 43184 non-null  int64
 1   Age                                 43184 non-null  int64
 2   person_id                           43184 non-null  int64
 3   Gender                              43184 non-null  int32
 4   Subgroup                            43184 non-null  object
 5   absence_indicator                   43184 non-null  int64
 6   analytic_period_id                  43184 non-null  int64
 7   tenure                              43184 non-null  float64
 8   overtime                            43184 non-null  int64
 9   salary                              43184 non-null  float64
 10  performance_rating                  43184 non-null  int64
 11  BiometricScreeningParticipants      43184 non-null  int64
 12  HRQParticipants                     43184 non-null  int64
 13  lsbio_cholesterol                   43184 non-null  int64
 14  lsbio_glucose                       43184 non-null  int64
 15  lsbio_bp                            43184 non-null  int64
 16  lsbio_weight                        43184 non-null  int64
 17  lsbio_trig                          43184 non-null  int64
 18  lshrq_physact                       43184 non-null  int64
 19  lshrq_tobacco                       43184 non-null  int64
 20  lshrq_nutrition                     43184 non-null  int64
 21  lshrq_stress                        43184 non-null  int64
 22  lshrq_genHealth                     43184 non-null  int64
 23  lshrq_wellbeing                     43184 non-null  int64
 24  lshrq_alcohol                       43184 non-null  int64
 25  lshrq_sleeping                      43184 non-null  int64
 26  cc_RespiratorySinusAllergy_chronic  43184 non-null  int64
 27  cc_diabetes                         43184 non-null  int64
 28  cc_cancer                           43184 non-null  int64
 29  cc_mskChronic                       43184 non-null  int64
 30  cc_cholesterol                      43184 non-null  int64
 31  cc_cardiac                          43184 non-null  int64
 32  cc_depression                       43184 non-null  int64
 33  cc_obesity                          43184 non-null  int64
 34  cc_mskAllOther                      43184 non-null  int64
 35  cc_behavioralAllOther               43184 non-null  int64
 36  cc_ckd                              43184 non-null  int64
 37  concurrent_risk                     43184 non-null  float64
 38  rx_nonClaimant                      43184 non-null  int64
 39  rx_nonCompliant                     43184 non-null  int64
 40  prog_1                              43184 non-null  int64
 41  prog_2                              43184 non-null  int64
 42  prog_3                              43184 non-null  int64
 43  prog_4                              43184 non-null  int64
 44  prog_5                              43184 non-null  int64
 45  prog_6                              43184 non-null  int64
 46  prog_7                              43184 non-null  int64
 47  prog_8                              43184 non-null  int64
 48  prog_9                              43184 non-null  int64
 49  prog_10                             43184 non-null  int64
 50  prog_11                             43184 non-null  int64
 51  prog_12                             43184 non-null  int64
 52  prog_13                             43184 non-null  int64
 53  prog_14                             43184 non-null  int64
 54  prog_15                             43184 non-null  int64
 55  prog_16                             43184 non-null  int64
 56  extreme_heat_2018                   43184 non-null  int64
 57  extreme_heat_2019                   43184 non-null  int64
 58  extreme_heat_2020                   43184 non-null  int64
 59  extreme_heat_ssp245_2025            43184 non-null  float64
 60  extreme_heat_ssp245_2035            43184 non-null  float64
 61  extreme_heat_ssp245_2045            43184 non-null  float64
 62  extreme_heat_ssp585_2025            43184 non-null  float64
 63  extreme_heat_ssp585_2035            43184 non-null  float64
 64  extreme_heat_ssp585_2045            43184 non-null  float64
 65  wildfire_potential_2018             43184 non-null  float64
 66  wildfire_potential_2019             43184 non-null  float64
 67  wildfire_potential_2019.1           43184 non-null  float64
 68  wildfire_potential_ssp245_2025      43184 non-null  float64
 69  wildfire_potential_ssp245_2035      43184 non-null  float64
 70  wildfire_potential_ssp245_2045      43184 non-null  float64
 71  wildfire_potential_ssp585_2025      43184 non-null  float64
 72  wildfire_potential_ssp585_2035      43184 non-null  float64
 73  wildfire_potential_ssp585_2045      43184 non-null  float64
dtypes: float64(18), int32(1), int64(54), object(1)
memory usage: 24.5+ MB

In [5]:
df.loc[df['person_id']==1006971219][['absence_indicator', 'person_id', 'analytic_period_id','cc_mskChronic']]

       absence_indicator   person_id  analytic_period_id  cc_mskChronic
208                    0  1006971219                   1              0
17430                  0  1006971219                   2              1
33807                 61  1006971219                   3              0

In [6]:
df = df.sort_values(by=['person_id', 'analytic_period_id'])

grouped = df.groupby('person_id')

health_factors = ['lsbio_cholesterol', 'lsbio_glucose', 'lsbio_bp', 'lsbio_weight', 'lsbio_trig', 'lshrq_physact', 'lshrq_tobacco', 'lshrq_nutrition', 
                  'lshrq_stress', 'lshrq_genHealth', 'lshrq_wellbeing', 'lshrq_alcohol', 'lshrq_sleeping', 'cc_RespiratorySinusAllergy_chronic', 
                  'cc_diabetes', 'cc_cancer', 'cc_mskChronic', 'cc_cholesterol', 'cc_cardiac', 'cc_depression', 'cc_obesity', 
                  'cc_mskAllOther', 'cc_behavioralAllOther', 'cc_ckd', 'concurrent_risk', 'rx_nonClaimant', 'rx_nonCompliant']

for person_id, group_df in grouped:
    for health in health_factors:
        if (group_df['analytic_period_id'] == 1).any() and (group_df.loc[group_df['analytic_period_id'] == 1, health] == 1).any():
            df.loc[(df['person_id'] == person_id) & (df['analytic_period_id'] != 1), health] = 1
        if (group_df['analytic_period_id'] == 2).any() and (group_df.loc[group_df['analytic_period_id'] == 2, health] == 1).any():
            df.loc[(df['person_id'] == person_id) & (df['analytic_period_id'] == 3), health] = 1

In [7]:
df.loc[df['person_id']==1006971219][['person_id', 'absence_indicator', 'analytic_period_id','cc_mskChronic']]

        person_id  absence_indicator  analytic_period_id  cc_mskChronic
208    1006971219                  0                   1              0
17430  1006971219                  0                   2              1
33807  1006971219                 61                   3              1

In [8]:
# df.to_csv('cleaned_dataset.csv')

In [9]:
df_P = df.loc[df['Subgroup']=='Subgroup P'].reset_index(drop=True)

df_P

,ADI,Age,person_id,Gender,Subgroup,absence_indicator,analytic_period_id,tenure,overtime,salary,...,extreme_heat_ssp585_2045,wildfire_potential_2018,wildfire_potential_2019,wildfire_potential_2019.1,wildfire_potential_ssp245_2025,wildfire_potential_ssp245_2035,wildfire_potential_ssp245_2045,wildfire_potential_ssp585_2025,wildfire_potential_ssp585_2035,wildfire_potential_ssp585_2045
0,57,28,1001121909,1,Subgroup P,0,1,5.91,5,89258.0,...,25.238094,9.104348,9.925000,10.091304,6.571641,6.881262,7.077469,6.625778,7.091410,7.391057
1,57,29,1001121909,1,Subgroup P,0,2,6.92,7,98688.0,...,25.238094,9.104348,9.925000,10.091304,6.571641,6.881262,7.077469,6.625778,7.091410,7.391057
2,57,30,1001121909,1,Subgroup P,20,3,7.92,7,108564.0,...,25.238094,9.104348,9.925000,10.091304,6.571641,6.881262,7.077469,6.625778,7.091410,7.391057
3,21,39,1002228813,1,Subgroup P,0,1,13.97,9,91517.0,...,11.601731,9.416304,9.723913,10.364130,6.024261,6.295128,6.427555,5.990173,6.326804,6.561169
4,21,39,1002228813,1,Subgroup P,0,2,14.97,9,91517.0,...,11.601731,9.416304,9.723913,10.364130,6.024261,6.295128,6.427555,5.990173,6.326804,6.561169
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19618,10,39,9998937334,1,Subgroup P,0,2,19.47,1,114457.0,...,11.601731,9.467391,9.460870,10.061957,6.024261,6.295128,6.427555,5.990173,6.326804,6.561169
19619,10,40,9998937334,1,Subgroup P,0,3,20.47,1,117892.0,...,11.601731,9.467391,9.460870,10.061957,6.024261,6.295128,6.427555,5.990173,6.326804,6.561169
19620,39,30,9999617900,1,Subgroup P,9,1,10.33,7,101031.0,...,17.796537,9.723913,9.852174,9.997826,6.341523,6.605085,6.750162,6.280464,6.651682,6.912897
19621,39,31,9999617900,1,Subgroup P,2,2,11.34,5,104062.0,...,17.796537,9.723913,9.852174,9.997826,6.341523,6.605085,6.750162,6.280464,6.651682,6.912897
19622,39,32,9999617900,1,Subgroup P,26,3,12.34,5,107186.0,...,17.796537,9.723913,9.852174,9.997826,6.341523,6.605085,6.750162,6.280464,6.651682,6.912897

In [10]:
df_C = df.loc[df['Subgroup']=='Subgroup C'].reset_index(drop=True)

df_C

,ADI,Age,person_id,Gender,Subgroup,absence_indicator,analytic_period_id,tenure,overtime,salary,...,extreme_heat_ssp585_2045,wildfire_potential_2018,wildfire_potential_2019,wildfire_potential_2019.1,wildfire_potential_ssp245_2025,wildfire_potential_ssp245_2035,wildfire_potential_ssp245_2045,wildfire_potential_ssp585_2025,wildfire_potential_ssp585_2035,wildfire_potential_ssp585_2045
0,19,24,1000028017,1,Subgroup C,0,1,8.652450,1,57232.24,...,4.012987,14.623913,12.133696,13.379348,12.986433,13.172131,13.369122,13.061731,13.215665,13.605292
1,0,51,1001534206,0,Subgroup C,79,1,20.228321,1,64418.00,...,36.411255,12.938043,10.883696,14.963043,9.908341,10.256216,10.625230,9.937467,10.390283,11.311178
2,55,52,1001534206,0,Subgroup C,0,2,21.228321,1,64418.00,...,36.411255,12.938043,10.883696,14.963043,9.908341,10.256216,10.625230,9.937467,10.390283,11.311178
3,32,41,1001889704,1,Subgroup C,0,1,5.930971,1,80000.00,...,75.147190,15.253261,12.645652,13.888043,11.246546,11.606987,11.760611,11.311094,11.540871,11.855016
4,32,42,1001889704,1,Subgroup C,0,2,6.930971,1,80440.00,...,75.147190,15.253261,12.645652,13.888043,11.246546,11.606987,11.760611,11.311094,11.540871,11.855016
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23556,15,51,9998301213,1,Subgroup C,0,1,28.124445,1,64418.00,...,30.688313,10.855435,9.541304,10.464130,5.946371,6.226923,6.409194,6.043142,6.638751,7.272909
23557,15,52,9998301213,1,Subgroup C,124,2,29.124445,1,64418.00,...,30.688313,10.855435,9.541304,10.464130,5.946371,6.226923,6.409194,6.043142,6.638751,7.272909
23558,15,53,9998301213,1,Subgroup C,0,3,30.124445,1,64418.00,...,30.688313,10.855435,9.541304,10.464130,5.946371,6.226923,6.409194,6.043142,6.638751,7.272909
23559,19,46,9998854988,0,Subgroup C,0,1,29.504350,1,64418.00,...,20.675323,9.436957,10.442391,10.882609,6.356157,6.690404,6.895881,6.393089,6.865395,7.172376
23560,19,47,9998854988,0,Subgroup C,0,2,30.504350,1,64418.00,...,20.675323,9.436957,10.442391,10.882609,6.356157,6.690404,6.895881,6.393089,6.865395,7.172376

In [52]:
health_programs = ['prog_1', 'prog_2', 'prog_3', 'prog_4', 'prog_5', 'prog_6', 'prog_7', 'prog_8', 'prog_9', 
                   'prog_10', 'prog_11', 'prog_12', 'prog_13', 'prog_14', 'prog_15', 'prog_16']

### Subgroup P

#### cc_mskChronic

In [293]:
df_P_mskChronic = df_P.loc[(df_P['cc_mskChronic'] == 1) & 
                           (df_P['cc_diabetes'] == 0) & 
                           (df_P['cc_cardiac'] == 0)].reset_index(drop=True)

df_P_mskChronic = df_P_mskChronic.sort_values(by=['person_id', 'analytic_period_id'])

df_P_mskChronic['percentage_diff_absence'] = round((df_P_mskChronic.groupby('person_id')['absence_indicator'].diff() * -1),0)
df_P_mskChronic['percentage_diff_absence'] = df_P_mskChronic['percentage_diff_absence'].fillna(0)
df_P_mskChronic['percentage_diff_absence'] = np.where(df_P_mskChronic['percentage_diff_absence']== -0, 0, df_P_mskChronic['percentage_diff_absence'])
df_P_mskChronic[health_programs] = np.where(df_P_mskChronic[health_programs] == -1, 0, df_P_mskChronic[health_programs])

df_P_mskChronic

,ADI,Age,person_id,Gender,Subgroup,absence_indicator,analytic_period_id,tenure,overtime,salary,...,wildfire_potential_2018,wildfire_potential_2019,wildfire_potential_2019.1,wildfire_potential_ssp245_2025,wildfire_potential_ssp245_2035,wildfire_potential_ssp245_2045,wildfire_potential_ssp585_2025,wildfire_potential_ssp585_2035,wildfire_potential_ssp585_2045,percentage_diff_absence
0,28,39,1006971219,1,Subgroup P,0,2,7.15,1,131000.0,...,9.792391,9.869565,10.609783,6.076034,6.377780,6.529870,6.091510,6.460996,6.703535,0.0
1,28,40,1006971219,1,Subgroup P,61,3,8.15,1,135000.0,...,9.792391,9.869565,10.609783,6.076034,6.377780,6.529870,6.091510,6.460996,6.703535,-61.0
2,21,53,1010658764,1,Subgroup P,0,2,34.36,5,133600.0,...,10.078261,10.346739,10.439130,6.507597,6.792691,6.960008,6.481590,6.892562,7.170657,0.0
3,21,54,1010658764,1,Subgroup P,0,3,35.36,3,139300.0,...,10.078261,10.346739,10.439130,6.507597,6.792691,6.960008,6.481590,6.892562,7.170657,0.0
4,25,45,1013214811,1,Subgroup P,0,3,7.46,5,104300.0,...,9.088043,9.164130,10.404348,5.803466,6.141432,6.357934,5.922491,6.452889,6.790101,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4691,18,38,9995667595,1,Subgroup P,0,2,11.51,1,94014.0,...,8.704348,9.220652,10.250000,5.464575,5.759225,5.909338,5.546726,5.922153,6.124357,0.0
4692,18,39,9995667595,1,Subgroup P,0,3,12.51,7,96832.0,...,8.704348,9.220652,10.250000,5.464575,5.759225,5.909338,5.546726,5.922153,6.124357,0.0
4693,39,30,9999617900,1,Subgroup P,9,1,10.33,7,101031.0,...,9.723913,9.852174,9.997826,6.341523,6.605085,6.750162,6.280464,6.651682,6.912897,0.0
4694,39,31,9999617900,1,Subgroup P,2,2,11.34,5,104062.0,...,9.723913,9.852174,9.997826,6.341523,6.605085,6.750162,6.280464,6.651682,6.912897,7.0
4695,39,32,9999617900,1,Subgroup P,26,3,12.34,5,107186.0,...,9.723913,9.852174,9.997826,6.341523,6.605085,6.750162,6.280464,6.651682,6.912897,-24.0

In [49]:
counts = df_P_mskChronic.groupby('person_id')['analytic_period_id'].unique()
person_ids_with_both_periods = [pid for pid, periods in counts.items() if 1 in periods and 2 in periods]

df_P_mskChronic_1_2 = df_P_mskChronic[df_P_mskChronic['person_id'].isin(person_ids_with_both_periods)]
df_P_mskChronic_1_2.reset_index(drop=True, inplace=True)
df_P_mskChronic_1_2 = df_P_mskChronic_1_2.loc[(df_P_mskChronic_1_2['analytic_period_id']==1) | (df_P_mskChronic_1_2['analytic_period_id']==2)]

df_P_mskChronic_1_2

,ADI,Age,person_id,Gender,Subgroup,absence_indicator,analytic_period_id,tenure,overtime,salary,...,wildfire_potential_2018,wildfire_potential_2019,wildfire_potential_2019.1,wildfire_potential_ssp245_2025,wildfire_potential_ssp245_2035,wildfire_potential_ssp245_2045,wildfire_potential_ssp585_2025,wildfire_potential_ssp585_2035,wildfire_potential_ssp585_2045,percentage_diff_absence
0,29,31,1016218037,1,Subgroup P,0,1,10.18,7,89780.0,...,10.598913,10.661957,11.409783,6.064177,6.380910,6.548825,6.117186,6.522880,6.771772,0.0
1,29,32,1016218037,1,Subgroup P,0,2,11.18,5,92475.0,...,10.598913,10.661957,11.409783,6.064177,6.380910,6.548825,6.117186,6.522880,6.771772,0.0
3,36,54,1018774502,1,Subgroup P,0,1,6.60,1,59755.0,...,11.039130,11.023913,11.963043,6.069724,6.365864,6.512409,6.091926,6.469195,6.700504,0.0
4,36,55,1018774502,1,Subgroup P,0,2,7.61,1,65359.0,...,11.039130,11.023913,11.963043,6.069724,6.365864,6.512409,6.091926,6.469195,6.700504,0.0
5,23,41,1022209559,1,Subgroup P,0,1,16.71,7,114656.0,...,9.591304,9.711957,10.215217,6.024261,6.295128,6.427555,5.990173,6.326804,6.561169,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3028,21,30,9976128807,1,Subgroup P,0,2,8.20,5,109077.0,...,10.078261,10.346739,10.439130,6.507597,6.792691,6.960008,6.481590,6.892562,7.170657,0.0
3030,32,27,9981592837,1,Subgroup P,0,1,2.67,9,73301.0,...,10.684783,10.801087,11.683696,6.033403,6.347014,6.512159,6.093082,6.504460,6.743331,0.0
3031,32,28,9981592837,1,Subgroup P,0,2,3.67,7,86141.0,...,10.684783,10.801087,11.683696,6.033403,6.347014,6.512159,6.093082,6.504460,6.743331,0.0
3032,39,30,9999617900,1,Subgroup P,9,1,10.33,7,101031.0,...,9.723913,9.852174,9.997826,6.341523,6.605085,6.750162,6.280464,6.651682,6.912897,0.0
3033,39,31,9999617900,1,Subgroup P,2,2,11.34,5,104062.0,...,9.723913,9.852174,9.997826,6.341523,6.605085,6.750162,6.280464,6.651682,6.912897,7.0

In [60]:
health_comparison_factors = health_programs + ['person_id']

year_1 = df_P_mskChronic_1_2.loc[df_P_mskChronic_1_2['analytic_period_id']==1][health_comparison_factors].reset_index(drop=True)
year_2 = df_P_mskChronic_1_2.loc[df_P_mskChronic_1_2['analytic_period_id']==2]['percentage_diff_absence'].reset_index(drop=True)

df_1_2 = year_1.merge(year_2, left_index=True, right_index=True,
                 how='outer', suffixes=('', '_y'))

df_1_2.drop(df_1_2.filter(regex='_y$').columns, axis=1, inplace=True)

df_1_2

,prog_1,prog_2,prog_3,prog_4,prog_5,prog_6,prog_7,prog_8,prog_9,prog_10,prog_11,prog_12,prog_13,prog_14,prog_15,prog_16,person_id,percentage_diff_absence
0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1016218037,0.0
1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1018774502,0.0
2,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1022209559,0.0
3,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,1046629252,0.0
4,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1055041546,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1068,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,9974967241,6.0
1069,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,9975954824,0.0
1070,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,9976128807,0.0
1071,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,9981592837,0.0
1072,0,0,0,1,0,0,0,0,0,0,1,1,0,1,0,0,9999617900,7.0

In [64]:
counts = df_P_mskChronic.groupby('person_id')['analytic_period_id'].unique()
person_ids_with_both_periods = [pid for pid, periods in counts.items() if 2 in periods and 3 in periods]

df_P_mskChronic_2_3 = df_P_mskChronic[df_P_mskChronic['person_id'].isin(person_ids_with_both_periods)]
df_P_mskChronic_2_3.reset_index(drop=True, inplace=True)
df_P_mskChronic_2_3 = df_P_mskChronic_2_3.loc[(df_P_mskChronic_2_3['analytic_period_id']==2) | (df_P_mskChronic_2_3['analytic_period_id']==3)]

df_P_mskChronic_2_3

,ADI,Age,person_id,Gender,Subgroup,absence_indicator,analytic_period_id,tenure,overtime,salary,...,wildfire_potential_2018,wildfire_potential_2019,wildfire_potential_2019.1,wildfire_potential_ssp245_2025,wildfire_potential_ssp245_2035,wildfire_potential_ssp245_2045,wildfire_potential_ssp585_2025,wildfire_potential_ssp585_2035,wildfire_potential_ssp585_2045,percentage_diff_absence
0,28,39,1006971219,1,Subgroup P,0,2,7.15,1,131000.0,...,9.792391,9.869565,10.609783,6.076034,6.377780,6.529870,6.091510,6.460996,6.703535,0.0
1,28,40,1006971219,1,Subgroup P,61,3,8.15,1,135000.0,...,9.792391,9.869565,10.609783,6.076034,6.377780,6.529870,6.091510,6.460996,6.703535,-61.0
2,21,53,1010658764,1,Subgroup P,0,2,34.36,5,133600.0,...,10.078261,10.346739,10.439130,6.507597,6.792691,6.960008,6.481590,6.892562,7.170657,0.0
3,21,54,1010658764,1,Subgroup P,0,3,35.36,3,139300.0,...,10.078261,10.346739,10.439130,6.507597,6.792691,6.960008,6.481590,6.892562,7.170657,0.0
5,29,32,1016218037,1,Subgroup P,0,2,11.18,5,92475.0,...,10.598913,10.661957,11.409783,6.064177,6.380910,6.548825,6.117186,6.522880,6.771772,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3555,39,44,9995527821,1,Subgroup P,0,3,6.81,1,100200.0,...,9.908696,9.875000,10.858696,5.511195,5.851079,6.076424,5.649698,6.112522,6.391492,0.0
3556,18,38,9995667595,1,Subgroup P,0,2,11.51,1,94014.0,...,8.704348,9.220652,10.250000,5.464575,5.759225,5.909338,5.546726,5.922153,6.124357,0.0
3557,18,39,9995667595,1,Subgroup P,0,3,12.51,7,96832.0,...,8.704348,9.220652,10.250000,5.464575,5.759225,5.909338,5.546726,5.922153,6.124357,0.0
3559,39,31,9999617900,1,Subgroup P,2,2,11.34,5,104062.0,...,9.723913,9.852174,9.997826,6.341523,6.605085,6.750162,6.280464,6.651682,6.912897,7.0
3560,39,32,9999617900,1,Subgroup P,26,3,12.34,5,107186.0,...,9.723913,9.852174,9.997826,6.341523,6.605085,6.750162,6.280464,6.651682,6.912897,-24.0

In [70]:
year_2 = df_P_mskChronic_2_3.loc[df_P_mskChronic_2_3['analytic_period_id']==2][health_comparison_factors].reset_index(drop=True)
year_3 = df_P_mskChronic_2_3.loc[df_P_mskChronic_2_3['analytic_period_id']==3]['percentage_diff_absence'].reset_index(drop=True)

df_2_3 = year_2.merge(year_3, left_index=True, right_index=True,
                 how='outer', suffixes=('', '_y'))

df_2_3.drop(df_2_3.filter(regex='_y$').columns, axis=1, inplace=True)

df_2_3

,prog_1,prog_2,prog_3,prog_4,prog_5,prog_6,prog_7,prog_8,prog_9,prog_10,prog_11,prog_12,prog_13,prog_14,prog_15,prog_16,person_id,percentage_diff_absence
0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1006971219,-61.0
1,1,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,1010658764,0.0
2,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1016218037,-31.0
3,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1022209559,0.0
4,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,1046629252,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1331,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,9979213863,4.0
1332,0,0,0,1,1,0,0,0,0,0,1,0,0,1,0,0,9981383884,43.0
1333,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,9995527821,0.0
1334,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,9995667595,0.0
1335,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,9999617900,-24.0

In [71]:
# train data: 2019 - 2018
# test data: 2020 - 2019

# get data from person_id with both analytic_period_id 1 and 2

from sklearn.model_selection import train_test_split

y_train = pd.DataFrame(df_1_2['percentage_diff_absence'])
y_train.loc[y_train['percentage_diff_absence'] > 0, 'percentage_diff_absence'] = np.log(y_train.loc[y_train['percentage_diff_absence'] > 0, 'percentage_diff_absence'])
y_train.loc[y_train['percentage_diff_absence'] < 0, 'percentage_diff_absence'] = -np.log(-y_train.loc[y_train['percentage_diff_absence'] < 0, 'percentage_diff_absence'])
x_train = pd.DataFrame(df_1_2[health_programs])
x_train[health_programs] = x_train[health_programs].astype('category')

y_test = pd.DataFrame(df_2_3['percentage_diff_absence'])
y_test.loc[y_test['percentage_diff_absence'] > 0, 'percentage_diff_absence'] = np.log(y_test.loc[y_test['percentage_diff_absence'] > 0, 'percentage_diff_absence'])
y_test.loc[y_test['percentage_diff_absence'] < 0, 'percentage_diff_absence'] = -np.log(-y_test.loc[y_test['percentage_diff_absence'] < 0, 'percentage_diff_absence'])
x_test = pd.DataFrame(df_2_3[health_programs])
x_test[health_programs] = x_test[health_programs].astype('category')

print("Train Set :", y_train.shape, x_train.shape)
print("Test Set  :", y_test.shape, x_test.shape)

Train Set : (1073, 1) (1073, 16)
Test Set  : (1336, 1) (1336, 16)

In [72]:
# use Linear Regression

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

linreg = LinearRegression()

linreg.fit(x_train, y_train)

print('Intercept of Regression \t: b = ', linreg.intercept_)

y_train_pred = linreg.predict(x_train)
y_test_pred = linreg.predict(x_test)

# Check the Goodness of Fit (on Train Data)
print("Goodness of Fit of Model \tTrain Dataset")
print("Explained Variance (R^2) \t:", linreg.score(x_train, y_train))
print("Mean Squared Error (MSE) \t:", mean_squared_error(y_train, y_train_pred))
print()

# Check the Goodness of Fit (on Test Data)
print("Goodness of Fit of Model \tTest Dataset")
print("Explained Variance (R^2) \t:", linreg.score(x_test, y_test))
print("Mean Squared Error (MSE) \t:", mean_squared_error(y_test, y_test_pred))
print()

Intercept of Regression 	: b =  [-0.36127835]
Goodness of Fit of Model 	Train Dataset
Explained Variance (R^2) 	: 0.028902900869989923
Mean Squared Error (MSE) 	: 3.530325480984119

Goodness of Fit of Model 	Test Dataset
Explained Variance (R^2) 	: -0.02528653552495186
Mean Squared Error (MSE) 	: 3.412739552124439

In [73]:
import statsmodels.api as sm

x_train_with_constant = sm.add_constant(x_train)
model = sm.OLS(y_train, x_train_with_constant)
result = model.fit()

print(result.summary())

                               OLS Regression Results
===================================================================================
Dep. Variable:     percentage_diff_absence   R-squared:                       0.029
Model:                                 OLS   Adj. R-squared:                  0.021
Method:                      Least Squares   F-statistic:                     3.515
Date:                     Sat, 06 Apr 2024   Prob (F-statistic):           0.000265
Time:                             15:55:28   Log-Likelihood:                -2199.3
No. Observations:                     1073   AIC:                             4419.
Df Residuals:                         1063   BIC:                             4468.
Df Model:                                9
Covariance Type:                 nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         -0.3613      0.190     -1.899      0.058      -0.735       0.012
prog_1         0.1515      0.173      0.877      0.380      -0.187       0.490
prog_2         2.5392      0.509      4.985      0.000       1.540       3.539
prog_3      1.756e-16   1.25e-16      1.409      0.159   -6.89e-17     4.2e-16
prog_4        -0.0929      0.125     -0.743      0.457      -0.338       0.152
prog_5        -0.0043      0.317     -0.014      0.989      -0.626       0.618
prog_6         0.7561      0.429      1.763      0.078      -0.085       1.598
prog_7      6.131e-16   1.17e-16      5.252      0.000    3.84e-16    8.42e-16
prog_8      8.707e-16   1.99e-16      4.370      0.000     4.8e-16    1.26e-15
prog_9      5.917e-16   1.51e-16      3.907      0.000    2.95e-16    8.89e-16
prog_10             0          0        nan        nan           0           0
prog_11        0.2828      0.208      1.359      0.174      -0.126       0.691
prog_12       -0.0877      0.181     -0.485      0.628      -0.442       0.267
prog_13        0.1651      0.391      0.422      0.673      -0.602       0.933
prog_14       -0.1285      0.173     -0.742      0.458      -0.469       0.211
prog_15             0          0        nan        nan           0           0
prog_16             0          0        nan        nan           0           0
==============================================================================
Omnibus:                       25.444   Durbin-Watson:                   2.107
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               48.161
Skew:                          -0.124   Prob(JB):                     3.48e-11
Kurtosis:                       4.008   Cond. No.                          inf
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is      0. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

C:\Users\Willis\anaconda3\Lib\site-packages\statsmodels\regression\linear_model.py:1965: RuntimeWarning: divide by zero encountered in scalar divide
  return np.sqrt(eigvals[0]/eigvals[-1])

In [74]:
# use decision tree regressor

from sklearn.tree import DecisionTreeRegressor

decisiontreemodel = DecisionTreeRegressor(max_depth=3)
result = decisiontreemodel.fit(x_train, y_train)

y_train_pred = decisiontreemodel.predict(x_train)
train_mse = mean_squared_error(y_train_pred, y_train)
y_test_pred = decisiontreemodel.predict(x_test)
test_mse = mean_squared_error(y_test_pred, y_test)

print("Mean Squared Error (Train Dataset):", train_mse)
print("Mean Squared Error (Test Dataset):", test_mse)

Mean Squared Error (Train Dataset): 3.5202103440646964
Mean Squared Error (Test Dataset): 3.46336934730501

In [75]:
from sklearn.model_selection import GridSearchCV

param_grid = {'max_depth': range(1, 11)}

decisiontreemodel = DecisionTreeRegressor()

grid_search = GridSearchCV(estimator=decisiontreemodel, param_grid=param_grid, cv=5)

grid_search.fit(x_train, y_train)
best_max_depth = grid_search.best_params_['max_depth']

print("Best max_depth:", best_max_depth)

Best max_depth: 1

In [76]:
# use decision tree regressor

from sklearn.tree import DecisionTreeRegressor

decisiontreemodel = DecisionTreeRegressor(max_depth=1)
result = decisiontreemodel.fit(x_train, y_train)

y_train_pred = decisiontreemodel.predict(x_train)
train_mse = mean_squared_error(y_train_pred, y_train)
y_test_pred = decisiontreemodel.predict(x_test)
test_mse = mean_squared_error(y_test_pred, y_test)

print("Mean Squared Error (Train Dataset):", train_mse)
print("Mean Squared Error (Test Dataset):", test_mse)

Mean Squared Error (Train Dataset): 3.552353988396842
Mean Squared Error (Test Dataset): 3.3648964887691193

In [77]:
significant_variable = {}
significant_variable['significant_variables'] = []
fr = decisiontreemodel.feature_importances_ 
importance_dict = dict(zip(x_train.columns, fr))
for key in importance_dict:
    if importance_dict[key] > 0:
        significant_variable['significant_variables'].append(key)
        
print(significant_variable)

{'significant_variables': ['prog_2']}

In [78]:
from sklearn.ensemble import RandomForestRegressor

randomforest = RandomForestRegressor(n_estimators=100, max_depth=5, random_state=42)
randomforest.fit(x_train, y_train)

y_train_pred = randomforest.predict(x_train)
train_mse = mean_squared_error(y_train_pred, y_train)
y_test_pred = randomforest.predict(x_test)
test_mse = mean_squared_error(y_test_pred, y_test)

print("Mean Squared Error (Train Dataset):", train_mse)
print("Mean Squared Error (Test Dataset):", test_mse)

Mean Squared Error (Train Dataset): 3.459600042660284
Mean Squared Error (Test Dataset): 3.433845384786243

C:\Users\Willis\AppData\Local\Temp\ipykernel_26140\458196643.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  randomforest.fit(x_train, y_train)

In [79]:
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint

param_dist = {
    'n_estimators': randint(50, 200),
    'max_depth': [None] + list(range(5, 20)),
    'min_samples_split': randint(2, 20)
}

randomized_search = RandomizedSearchCV(estimator=RandomForestRegressor(), param_distributions=param_dist, n_iter=5, cv=5, scoring='neg_mean_squared_error', random_state=42)

randomized_search.fit(x_train, y_train)

best_params = randomized_search.best_params_
print(best_params)

C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:909: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self.best_estimator_.fit(X, y, **fit_params)

{'max_depth': 6, 'min_samples_split': 12, 'n_estimators': 137}

In [80]:
randomforest = RandomForestRegressor(n_estimators=best_params['n_estimators'], max_depth=best_params['max_depth'], min_samples_split=best_params['min_samples_split'], random_state=42)
randomforest.fit(x_train, y_train)

y_train_pred = randomforest.predict(x_train)
train_mse = mean_squared_error(y_train_pred, y_train)
y_test_pred = randomforest.predict(x_test)
test_mse = mean_squared_error(y_test_pred, y_test)

print("Mean Squared Error (Train Dataset):", train_mse)
print("Mean Squared Error (Test Dataset):", test_mse)

Mean Squared Error (Train Dataset): 3.478168692484316
Mean Squared Error (Test Dataset): 3.411504435679174

C:\Users\Willis\AppData\Local\Temp\ipykernel_26140\3010193299.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  randomforest.fit(x_train, y_train)

In [81]:
feature_importances = randomforest.feature_importances_
feature_importance_dict = dict(zip(x_train.columns, feature_importances))
sorted_features = sorted(feature_importance_dict.items(), key=lambda x: x[1], reverse=True)

sorted_features

[('prog_2', 0.43445569187074556),
 ('prog_4', 0.08957634833343166),
 ('prog_12', 0.07794254883270464),
 ('prog_1', 0.07640311843603426),
 ('prog_13', 0.07501547931594743),
 ('prog_6', 0.07480650822256484),
 ('prog_14', 0.061624353364577326),
 ('prog_5', 0.05664838998916166),
 ('prog_11', 0.053527561634832695),
 ('prog_3', 0.0),
 ('prog_7', 0.0),
 ('prog_8', 0.0),
 ('prog_9', 0.0),
 ('prog_10', 0.0),
 ('prog_15', 0.0),
 ('prog_16', 0.0)]

#### cc_cardiac

In [82]:
df_P_cardiac = df_P.loc[(df_P['cc_mskChronic'] == 0) & 
                           (df_P['cc_diabetes'] == 0) & 
                           (df_P['cc_cardiac'] == 1)].reset_index(drop=True)

df_P_cardiac = df_P_cardiac.sort_values(by=['person_id', 'analytic_period_id'])

df_P_cardiac['percentage_diff_absence'] = round((df_P_cardiac.groupby('person_id')['absence_indicator'].diff() * -1),0)
df_P_cardiac['percentage_diff_absence'] = df_P_cardiac['percentage_diff_absence'].fillna(0)
df_P_cardiac['percentage_diff_absence'] = np.where(df_P_cardiac['percentage_diff_absence']== -0, 0, df_P_cardiac['percentage_diff_absence'])
df_P_cardiac[health_programs] = np.where(df_P_cardiac[health_programs] == -1, 0, df_P_cardiac[health_programs])

df_P_cardiac

,ADI,Age,person_id,Gender,Subgroup,absence_indicator,analytic_period_id,tenure,overtime,salary,...,wildfire_potential_2018,wildfire_potential_2019,wildfire_potential_2019.1,wildfire_potential_ssp245_2025,wildfire_potential_ssp245_2035,wildfire_potential_ssp245_2045,wildfire_potential_ssp585_2025,wildfire_potential_ssp585_2035,wildfire_potential_ssp585_2045,percentage_diff_absence
0,21,39,1002228813,1,Subgroup P,0,1,13.97,9,91517.0,...,9.416304,9.723913,10.364130,6.024261,6.295128,6.427555,5.990173,6.326804,6.561169,0.0
1,21,39,1002228813,1,Subgroup P,0,2,14.97,9,91517.0,...,9.416304,9.723913,10.364130,6.024261,6.295128,6.427555,5.990173,6.326804,6.561169,0.0
2,21,40,1002228813,1,Subgroup P,0,3,15.97,1,100267.0,...,9.416304,9.723913,10.364130,6.024261,6.295128,6.427555,5.990173,6.326804,6.561169,0.0
3,16,49,1013355764,1,Subgroup P,0,1,6.51,9,89780.0,...,9.604348,9.885870,11.138043,6.033403,6.347014,6.512159,6.093082,6.504460,6.743331,0.0
4,16,50,1013355764,1,Subgroup P,0,2,7.51,7,92475.0,...,9.604348,9.885870,11.138043,6.033403,6.347014,6.512159,6.093082,6.504460,6.743331,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1876,21,48,9969609699,1,Subgroup P,0,1,19.98,1,79176.0,...,10.758696,10.884783,11.782609,6.033403,6.347014,6.512159,6.093082,6.504460,6.743331,0.0
1877,20,42,9987838531,1,Subgroup P,1,1,18.23,9,81625.0,...,8.841304,9.010870,10.806522,5.509268,5.825750,6.010160,5.613933,6.039884,6.277661,0.0
1878,10,38,9998937334,1,Subgroup P,0,1,18.46,1,111123.0,...,9.467391,9.460870,10.061957,6.024261,6.295128,6.427555,5.990173,6.326804,6.561169,0.0
1879,10,39,9998937334,1,Subgroup P,0,2,19.47,1,114457.0,...,9.467391,9.460870,10.061957,6.024261,6.295128,6.427555,5.990173,6.326804,6.561169,0.0
1880,10,40,9998937334,1,Subgroup P,0,3,20.47,1,117892.0,...,9.467391,9.460870,10.061957,6.024261,6.295128,6.427555,5.990173,6.326804,6.561169,0.0

In [83]:
counts = df_P_cardiac.groupby('person_id')['analytic_period_id'].unique()
person_ids_with_both_periods = [pid for pid, periods in counts.items() if 1 in periods and 2 in periods]

df_P_cardiac_1_2 = df_P_cardiac[df_P_cardiac['person_id'].isin(person_ids_with_both_periods)]
df_P_cardiac_1_2.reset_index(drop=True, inplace=True)
df_P_cardiac_1_2 = df_P_cardiac_1_2.loc[(df_P_cardiac_1_2['analytic_period_id']==1) | (df_P_cardiac_1_2['analytic_period_id']==2)]

df_P_cardiac_1_2

,ADI,Age,person_id,Gender,Subgroup,absence_indicator,analytic_period_id,tenure,overtime,salary,...,wildfire_potential_2018,wildfire_potential_2019,wildfire_potential_2019.1,wildfire_potential_ssp245_2025,wildfire_potential_ssp245_2035,wildfire_potential_ssp245_2045,wildfire_potential_ssp585_2025,wildfire_potential_ssp585_2035,wildfire_potential_ssp585_2045,percentage_diff_absence
0,21,39,1002228813,1,Subgroup P,0,1,13.97,9,91517.0,...,9.416304,9.723913,10.364130,6.024261,6.295128,6.427555,5.990173,6.326804,6.561169,0.0
1,21,39,1002228813,1,Subgroup P,0,2,14.97,9,91517.0,...,9.416304,9.723913,10.364130,6.024261,6.295128,6.427555,5.990173,6.326804,6.561169,0.0
3,16,49,1013355764,1,Subgroup P,0,1,6.51,9,89780.0,...,9.604348,9.885870,11.138043,6.033403,6.347014,6.512159,6.093082,6.504460,6.743331,0.0
4,16,50,1013355764,1,Subgroup P,0,2,7.51,7,92475.0,...,9.604348,9.885870,11.138043,6.033403,6.347014,6.512159,6.093082,6.504460,6.743331,0.0
6,22,35,1059113204,1,Subgroup P,1,1,6.41,7,98047.0,...,10.697826,10.611957,11.314130,6.076034,6.377780,6.529870,6.091510,6.460996,6.703535,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1098,26,57,9915070787,1,Subgroup P,0,2,18.50,1,69532.0,...,10.579348,10.857609,11.808696,6.033403,6.347014,6.512159,6.093082,6.504460,6.743331,0.0
1100,14,59,9968402192,1,Subgroup P,35,1,15.77,1,67507.0,...,9.922826,10.658696,11.467391,6.033403,6.347014,6.512159,6.093082,6.504460,6.743331,0.0
1101,14,60,9968402192,1,Subgroup P,0,2,16.77,1,69532.0,...,9.922826,10.658696,11.467391,6.033403,6.347014,6.512159,6.093082,6.504460,6.743331,35.0
1102,10,38,9998937334,1,Subgroup P,0,1,18.46,1,111123.0,...,9.467391,9.460870,10.061957,6.024261,6.295128,6.427555,5.990173,6.326804,6.561169,0.0
1103,10,39,9998937334,1,Subgroup P,0,2,19.47,1,114457.0,...,9.467391,9.460870,10.061957,6.024261,6.295128,6.427555,5.990173,6.326804,6.561169,0.0

In [84]:
year_1 = df_P_cardiac_1_2.loc[df_P_cardiac_1_2['analytic_period_id']==1][health_comparison_factors].reset_index(drop=True)
year_2 = df_P_cardiac_1_2.loc[df_P_cardiac_1_2['analytic_period_id']==2]['percentage_diff_absence'].reset_index(drop=True)

df_1_2 = year_1.merge(year_2, left_index=True, right_index=True,
                 how='outer', suffixes=('', '_y'))

df_1_2.drop(df_1_2.filter(regex='_y$').columns, axis=1, inplace=True)

df_1_2

,prog_1,prog_2,prog_3,prog_4,prog_5,prog_6,prog_7,prog_8,prog_9,prog_10,prog_11,prog_12,prog_13,prog_14,prog_15,prog_16,person_id,percentage_diff_absence
0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1002228813,0.0
1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1013355764,0.0
2,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1059113204,1.0
3,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1066220734,-30.0
4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1094010974,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
396,1,0,0,1,0,0,0,0,0,0,1,0,0,1,0,0,9811469926,0.0
397,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,9875285941,0.0
398,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,9915070787,0.0
399,0,0,0,1,0,0,0,0,0,0,1,1,0,0,0,0,9968402192,35.0
400,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,9998937334,0.0

In [85]:
counts = df_P_cardiac.groupby('person_id')['analytic_period_id'].unique()
person_ids_with_both_periods = [pid for pid, periods in counts.items() if 2 in periods and 3 in periods]

df_P_cardiac_2_3 = df_P_cardiac[df_P_cardiac['person_id'].isin(person_ids_with_both_periods)]
df_P_cardiac_2_3.reset_index(drop=True, inplace=True)
df_P_cardiac_2_3 = df_P_cardiac_2_3.loc[(df_P_cardiac_2_3['analytic_period_id']==2) | (df_P_cardiac_2_3['analytic_period_id']==3)]

df_P_cardiac_2_3

,ADI,Age,person_id,Gender,Subgroup,absence_indicator,analytic_period_id,tenure,overtime,salary,...,wildfire_potential_2018,wildfire_potential_2019,wildfire_potential_2019.1,wildfire_potential_ssp245_2025,wildfire_potential_ssp245_2035,wildfire_potential_ssp245_2045,wildfire_potential_ssp585_2025,wildfire_potential_ssp585_2035,wildfire_potential_ssp585_2045,percentage_diff_absence
1,21,39,1002228813,1,Subgroup P,0,2,14.97,9,91517.0,...,9.416304,9.723913,10.364130,6.024261,6.295128,6.427555,5.990173,6.326804,6.561169,0.0
2,21,40,1002228813,1,Subgroup P,0,3,15.97,1,100267.0,...,9.416304,9.723913,10.364130,6.024261,6.295128,6.427555,5.990173,6.326804,6.561169,0.0
4,16,50,1013355764,1,Subgroup P,0,2,7.51,7,92475.0,...,9.604348,9.885870,11.138043,6.033403,6.347014,6.512159,6.093082,6.504460,6.743331,0.0
5,16,51,1013355764,1,Subgroup P,0,3,8.52,7,95250.0,...,9.604348,9.885870,11.138043,6.033403,6.347014,6.512159,6.093082,6.504460,6.743331,0.0
7,22,36,1059113204,1,Subgroup P,0,2,7.42,7,107720.0,...,10.697826,10.611957,11.314130,6.076034,6.377780,6.529870,6.091510,6.460996,6.703535,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1219,26,58,9915070787,1,Subgroup P,0,3,19.51,1,71620.0,...,10.579348,10.857609,11.808696,6.033403,6.347014,6.512159,6.093082,6.504460,6.743331,0.0
1220,66,62,9926087342,1,Subgroup P,2,2,30.42,3,116400.0,...,10.351087,10.195652,10.829348,6.183942,6.481849,6.642996,6.176941,6.562165,6.822476,0.0
1221,66,63,9926087342,1,Subgroup P,54,3,31.42,3,119900.0,...,10.351087,10.195652,10.829348,6.183942,6.481849,6.642996,6.176941,6.562165,6.822476,-52.0
1223,10,39,9998937334,1,Subgroup P,0,2,19.47,1,114457.0,...,9.467391,9.460870,10.061957,6.024261,6.295128,6.427555,5.990173,6.326804,6.561169,0.0
1224,10,40,9998937334,1,Subgroup P,0,3,20.47,1,117892.0,...,9.467391,9.460870,10.061957,6.024261,6.295128,6.427555,5.990173,6.326804,6.561169,0.0

In [86]:
year_2 = df_P_cardiac_2_3.loc[df_P_cardiac_2_3['analytic_period_id']==2][health_comparison_factors].reset_index(drop=True)
year_3 = df_P_cardiac_2_3.loc[df_P_cardiac_2_3['analytic_period_id']==3]['percentage_diff_absence'].reset_index(drop=True)

df_2_3 = year_2.merge(year_3, left_index=True, right_index=True,
                 how='outer', suffixes=('', '_y'))

df_2_3.drop(df_2_3.filter(regex='_y$').columns, axis=1, inplace=True)

df_2_3

,prog_1,prog_2,prog_3,prog_4,prog_5,prog_6,prog_7,prog_8,prog_9,prog_10,prog_11,prog_12,prog_13,prog_14,prog_15,prog_16,person_id,percentage_diff_absence
0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,1002228813,0.0
1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1013355764,0.0
2,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1059113204,0.0
3,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1089784415,53.0
4,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1094010974,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
456,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,9875285941,0.0
457,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,9913971787,0.0
458,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,9915070787,0.0
459,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,9926087342,-52.0
460,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,9998937334,0.0

In [87]:
# train data: 2019 - 2018
# test data: 2020 - 2019

# get data from person_id with both analytic_period_id 1 and 2

from sklearn.model_selection import train_test_split

y_train = pd.DataFrame(df_1_2['percentage_diff_absence'])
y_train.loc[y_train['percentage_diff_absence'] > 0, 'percentage_diff_absence'] = np.log(y_train.loc[y_train['percentage_diff_absence'] > 0, 'percentage_diff_absence'])
y_train.loc[y_train['percentage_diff_absence'] < 0, 'percentage_diff_absence'] = -np.log(-y_train.loc[y_train['percentage_diff_absence'] < 0, 'percentage_diff_absence'])
x_train = pd.DataFrame(df_1_2[health_programs])
x_train[health_programs] = x_train[health_programs].astype('category')

y_test = pd.DataFrame(df_2_3['percentage_diff_absence'])
y_test.loc[y_test['percentage_diff_absence'] > 0, 'percentage_diff_absence'] = np.log(y_test.loc[y_test['percentage_diff_absence'] > 0, 'percentage_diff_absence'])
y_test.loc[y_test['percentage_diff_absence'] < 0, 'percentage_diff_absence'] = -np.log(-y_test.loc[y_test['percentage_diff_absence'] < 0, 'percentage_diff_absence'])
x_test = pd.DataFrame(df_2_3[health_programs])
x_test[health_programs] = x_test[health_programs].astype('category')

print("Train Set :", y_train.shape, x_train.shape)
print("Test Set  :", y_test.shape, x_test.shape)

Train Set : (401, 1) (401, 16)
Test Set  : (461, 1) (461, 16)

In [88]:
# use Linear Regression

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

linreg = LinearRegression()

linreg.fit(x_train, y_train)

print('Intercept of Regression \t: b = ', linreg.intercept_)

y_train_pred = linreg.predict(x_train)
y_test_pred = linreg.predict(x_test)

# Check the Goodness of Fit (on Train Data)
print("Goodness of Fit of Model \tTrain Dataset")
print("Explained Variance (R^2) \t:", linreg.score(x_train, y_train))
print("Mean Squared Error (MSE) \t:", mean_squared_error(y_train, y_train_pred))
print()

# Check the Goodness of Fit (on Test Data)
print("Goodness of Fit of Model \tTest Dataset")
print("Explained Variance (R^2) \t:", linreg.score(x_test, y_test))
print("Mean Squared Error (MSE) \t:", mean_squared_error(y_test, y_test_pred))
print()

Intercept of Regression 	: b =  [-0.19292796]
Goodness of Fit of Model 	Train Dataset
Explained Variance (R^2) 	: 0.03582880057589455
Mean Squared Error (MSE) 	: 1.9040236502972865

Goodness of Fit of Model 	Test Dataset
Explained Variance (R^2) 	: -0.20533893891980637
Mean Squared Error (MSE) 	: 2.1618613433897553

In [89]:
import statsmodels.api as sm

x_train_with_constant = sm.add_constant(x_train)
model = sm.OLS(y_train, x_train_with_constant)
result = model.fit()

print(result.summary())

                               OLS Regression Results
===================================================================================
Dep. Variable:     percentage_diff_absence   R-squared:                       0.036
Model:                                 OLS   Adj. R-squared:                  0.014
Method:                      Least Squares   F-statistic:                     1.614
Date:                     Sat, 06 Apr 2024   Prob (F-statistic):              0.109
Time:                             16:36:47   Log-Likelihood:                -698.11
No. Observations:                      401   AIC:                             1416.
Df Residuals:                          391   BIC:                             1456.
Df Model:                                9
Covariance Type:                 nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         -0.1929      0.173     -1.117      0.265      -0.533       0.147
prog_1        -0.0470      0.293     -0.160      0.873      -0.624       0.530
prog_2        -1.8014      0.817     -2.206      0.028      -3.407      -0.196
prog_3      5.681e-16   2.77e-16      2.048      0.041    2.26e-17    1.11e-15
prog_4         0.2007      0.168      1.197      0.232      -0.129       0.530
prog_5        -0.3791      0.359     -1.056      0.291      -1.085       0.326
prog_6        -1.4035      1.016     -1.382      0.168      -3.400       0.593
prog_7      4.931e-17   1.35e-16      0.365      0.716   -2.17e-16    3.15e-16
prog_8      3.778e-17   2.83e-17      1.336      0.182   -1.78e-17    9.34e-17
prog_9      2.957e-16   2.26e-16      1.307      0.192   -1.49e-16     7.4e-16
prog_10             0          0        nan        nan           0           0
prog_11        0.1088      0.199      0.546      0.585      -0.283       0.500
prog_12        0.0522      0.257      0.203      0.839      -0.453       0.558
prog_13        0.7115      0.412      1.726      0.085      -0.099       1.522
prog_14       -0.2291      0.263     -0.870      0.385      -0.747       0.289
prog_15             0          0        nan        nan           0           0
prog_16             0          0        nan        nan           0           0
==============================================================================
Omnibus:                       38.331   Durbin-Watson:                   1.993
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              195.845
Skew:                          -0.095   Prob(JB):                     2.97e-43
Kurtosis:                       6.418   Cond. No.                          inf
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is      0. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

C:\Users\Willis\anaconda3\Lib\site-packages\statsmodels\regression\linear_model.py:1965: RuntimeWarning: divide by zero encountered in scalar divide
  return np.sqrt(eigvals[0]/eigvals[-1])

In [90]:
# use decision tree regressor

from sklearn.tree import DecisionTreeRegressor

decisiontreemodel = DecisionTreeRegressor(max_depth=3)
result = decisiontreemodel.fit(x_train, y_train)

y_train_pred = decisiontreemodel.predict(x_train)
train_mse = mean_squared_error(y_train_pred, y_train)
y_test_pred = decisiontreemodel.predict(x_test)
test_mse = mean_squared_error(y_test_pred, y_test)

print("Mean Squared Error (Train Dataset):", train_mse)
print("Mean Squared Error (Test Dataset):", test_mse)

Mean Squared Error (Train Dataset): 1.7785953119424078
Mean Squared Error (Test Dataset): 2.504408679574423

In [91]:
from sklearn.model_selection import GridSearchCV

param_grid = {'max_depth': range(1, 11)}

decisiontreemodel = DecisionTreeRegressor()

grid_search = GridSearchCV(estimator=decisiontreemodel, param_grid=param_grid, cv=5)

grid_search.fit(x_train, y_train)
best_max_depth = grid_search.best_params_['max_depth']

print("Best max_depth:", best_max_depth)

Best max_depth: 1

In [92]:
# use decision tree regressor

from sklearn.tree import DecisionTreeRegressor

decisiontreemodel = DecisionTreeRegressor(max_depth=1)
result = decisiontreemodel.fit(x_train, y_train)

y_train_pred = decisiontreemodel.predict(x_train)
train_mse = mean_squared_error(y_train_pred, y_train)
y_test_pred = decisiontreemodel.predict(x_test)
test_mse = mean_squared_error(y_test_pred, y_test)

print("Mean Squared Error (Train Dataset):", train_mse)
print("Mean Squared Error (Test Dataset):", test_mse)

Mean Squared Error (Train Dataset): 1.9499455399967278
Mean Squared Error (Test Dataset): 2.0917071594601255

In [93]:
significant_variable = {}
significant_variable['significant_variables'] = []
fr = decisiontreemodel.feature_importances_ 
importance_dict = dict(zip(x_train.columns, fr))
for key in importance_dict:
    if importance_dict[key] > 0:
        significant_variable['significant_variables'].append(key)
        
print(significant_variable)

{'significant_variables': ['prog_2']}

In [94]:
from sklearn.ensemble import RandomForestRegressor

randomforest = RandomForestRegressor(n_estimators=100, max_depth=5, random_state=42)
randomforest.fit(x_train, y_train)

y_train_pred = randomforest.predict(x_train)
train_mse = mean_squared_error(y_train_pred, y_train)
y_test_pred = randomforest.predict(x_test)
test_mse = mean_squared_error(y_test_pred, y_test)

print("Mean Squared Error (Train Dataset):", train_mse)
print("Mean Squared Error (Test Dataset):", test_mse)

Mean Squared Error (Train Dataset): 1.75839421860449
Mean Squared Error (Test Dataset): 2.1370742019387343

C:\Users\Willis\AppData\Local\Temp\ipykernel_26140\458196643.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  randomforest.fit(x_train, y_train)

In [95]:
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint

param_dist = {
    'n_estimators': randint(50, 200),
    'max_depth': [None] + list(range(5, 20)),
    'min_samples_split': randint(2, 20)
}

randomized_search = RandomizedSearchCV(estimator=RandomForestRegressor(), param_distributions=param_dist, n_iter=5, cv=5, scoring='neg_mean_squared_error', random_state=42)

randomized_search.fit(x_train, y_train)

best_params = randomized_search.best_params_
print(best_params)

C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)

{'max_depth': 6, 'min_samples_split': 12, 'n_estimators': 137}

C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:909: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self.best_estimator_.fit(X, y, **fit_params)

In [96]:
randomforest = RandomForestRegressor(n_estimators=best_params['n_estimators'], max_depth=best_params['max_depth'], min_samples_split=best_params['min_samples_split'], random_state=42)
randomforest.fit(x_train, y_train)

y_train_pred = randomforest.predict(x_train)
train_mse = mean_squared_error(y_train_pred, y_train)
y_test_pred = randomforest.predict(x_test)
test_mse = mean_squared_error(y_test_pred, y_test)

print("Mean Squared Error (Train Dataset):", train_mse)
print("Mean Squared Error (Test Dataset):", test_mse)

Mean Squared Error (Train Dataset): 1.8292634773917837
Mean Squared Error (Test Dataset): 2.2304494736466025

C:\Users\Willis\AppData\Local\Temp\ipykernel_26140\3010193299.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  randomforest.fit(x_train, y_train)

In [97]:
feature_importances = randomforest.feature_importances_
feature_importance_dict = dict(zip(x_train.columns, feature_importances))
sorted_features = sorted(feature_importance_dict.items(), key=lambda x: x[1], reverse=True)

sorted_features

[('prog_2', 0.44515385406902297),
 ('prog_13', 0.12977343117061996),
 ('prog_6', 0.12158695896338129),
 ('prog_12', 0.10350136911904856),
 ('prog_4', 0.08538266887278557),
 ('prog_14', 0.0381586731641474),
 ('prog_11', 0.027252783588920988),
 ('prog_5', 0.024649833353894625),
 ('prog_1', 0.024540427698178595),
 ('prog_3', 0.0),
 ('prog_7', 0.0),
 ('prog_8', 0.0),
 ('prog_9', 0.0),
 ('prog_10', 0.0),
 ('prog_15', 0.0),
 ('prog_16', 0.0)]

#### cc_diabetes

In [98]:
df_P_diabetes = df_P.loc[(df_P['cc_mskChronic'] == 0) & 
                           (df_P['cc_diabetes'] == 1) & 
                           (df_P['cc_cardiac'] == 0)].reset_index(drop=True)

df_P_diabetes = df_P_diabetes.sort_values(by=['person_id', 'analytic_period_id'])

df_P_diabetes['percentage_diff_absence'] = round((df_P_diabetes.groupby('person_id')['absence_indicator'].diff() * -1),0)
df_P_diabetes['percentage_diff_absence'] = df_P_diabetes['percentage_diff_absence'].fillna(0)
df_P_diabetes['percentage_diff_absence'] = np.where(df_P_diabetes['percentage_diff_absence']== -0, 0, df_P_diabetes['percentage_diff_absence'])
df_P_diabetes[health_programs] = np.where(df_P_diabetes[health_programs] == -1, 0, df_P_diabetes[health_programs])

df_P_diabetes

,ADI,Age,person_id,Gender,Subgroup,absence_indicator,analytic_period_id,tenure,overtime,salary,...,wildfire_potential_2018,wildfire_potential_2019,wildfire_potential_2019.1,wildfire_potential_ssp245_2025,wildfire_potential_ssp245_2035,wildfire_potential_ssp245_2045,wildfire_potential_ssp585_2025,wildfire_potential_ssp585_2035,wildfire_potential_ssp585_2045,percentage_diff_absence
0,54,61,1022476732,1,Subgroup P,0,1,29.97,1,95886.0,...,10.357609,10.117391,11.296739,5.969366,6.312764,6.527190,6.068531,6.580319,6.904758,0.0
1,54,63,1022476732,1,Subgroup P,0,3,31.98,1,95250.0,...,10.357609,10.117391,11.296739,5.969366,6.312764,6.527190,6.068531,6.580319,6.904758,0.0
2,42,59,1048340555,1,Subgroup P,0,1,40.17,5,102329.0,...,10.655435,10.870652,11.047826,6.346673,6.668234,6.856681,6.359701,6.796207,7.083618,0.0
3,56,56,1273770367,1,Subgroup P,0,1,8.55,3,98087.0,...,10.432609,10.693478,11.592391,6.566475,6.882546,7.078842,6.570887,7.018056,7.308116,0.0
4,56,58,1273770367,1,Subgroup P,0,3,10.55,1,98087.0,...,10.432609,10.693478,11.592391,6.566475,6.882546,7.078842,6.570887,7.018056,7.308116,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
303,33,42,9851594768,1,Subgroup P,0,3,19.84,7,95250.0,...,10.958696,11.210870,11.951087,6.064177,6.380910,6.548825,6.117186,6.522880,6.771772,0.0
304,59,63,9932998550,1,Subgroup P,21,1,4.18,3,69733.0,...,9.475000,10.422826,9.479348,6.474419,6.735523,6.870221,6.420973,6.801326,7.076184,0.0
305,22,35,9941321236,1,Subgroup P,0,1,10.37,7,104582.0,...,10.813043,11.010870,11.734783,6.033403,6.347014,6.512159,6.093082,6.504460,6.743331,0.0
306,24,36,9941321236,1,Subgroup P,0,2,11.37,7,107720.0,...,10.334783,10.867391,12.040217,6.033403,6.347014,6.512159,6.093082,6.504460,6.743331,0.0
307,21,37,9941321236,1,Subgroup P,0,3,12.38,5,110952.0,...,8.630435,8.752174,9.706522,5.509268,5.825750,6.010160,5.613933,6.039884,6.277661,0.0

In [99]:
counts = df_P_diabetes.groupby('person_id')['analytic_period_id'].unique()
person_ids_with_both_periods = [pid for pid, periods in counts.items() if 1 in periods and 2 in periods]

df_P_diabetes_1_2 = df_P_diabetes[df_P_diabetes['person_id'].isin(person_ids_with_both_periods)]
df_P_diabetes_1_2.reset_index(drop=True, inplace=True)
df_P_diabetes_1_2 = df_P_diabetes_1_2.loc[(df_P_diabetes_1_2['analytic_period_id']==1) | (df_P_diabetes_1_2['analytic_period_id']==2)]

df_P_diabetes_1_2

,ADI,Age,person_id,Gender,Subgroup,absence_indicator,analytic_period_id,tenure,overtime,salary,...,wildfire_potential_2018,wildfire_potential_2019,wildfire_potential_2019.1,wildfire_potential_ssp245_2025,wildfire_potential_ssp245_2035,wildfire_potential_ssp245_2045,wildfire_potential_ssp585_2025,wildfire_potential_ssp585_2035,wildfire_potential_ssp585_2045,percentage_diff_absence
0,29,45,1503852073,1,Subgroup P,21,1,9.39,7,101031.0,...,8.498913,8.429348,9.579348,5.509268,5.825750,6.010160,5.613933,6.039884,6.277661,0.0
1,29,46,1503852073,1,Subgroup P,0,2,10.39,7,104062.0,...,8.498913,8.429348,9.579348,5.509268,5.825750,6.010160,5.613933,6.039884,6.277661,21.0
2,32,32,1612242838,0,Subgroup P,27,1,10.62,1,53276.0,...,11.018478,11.153261,11.892391,6.069724,6.365864,6.512409,6.091926,6.469195,6.700504,0.0
3,32,33,1612242838,0,Subgroup P,110,2,11.62,1,54876.0,...,11.018478,11.153261,11.892391,6.069724,6.365864,6.512409,6.091926,6.469195,6.700504,-83.0
5,20,30,1878767656,0,Subgroup P,0,1,6.22,1,98000.0,...,9.895652,9.854348,10.597826,6.123318,6.446156,6.621974,6.162228,6.574199,6.841721,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,25,51,9708101272,1,Subgroup P,0,2,7.43,7,92475.0,...,9.953261,10.131522,10.935870,6.064177,6.380910,6.548825,6.117186,6.522880,6.771772,0.0
177,33,40,9851594768,1,Subgroup P,0,1,17.83,5,89780.0,...,10.958696,11.210870,11.951087,6.064177,6.380910,6.548825,6.117186,6.522880,6.771772,0.0
178,33,41,9851594768,1,Subgroup P,0,2,18.83,7,92475.0,...,10.958696,11.210870,11.951087,6.064177,6.380910,6.548825,6.117186,6.522880,6.771772,0.0
180,22,35,9941321236,1,Subgroup P,0,1,10.37,7,104582.0,...,10.813043,11.010870,11.734783,6.033403,6.347014,6.512159,6.093082,6.504460,6.743331,0.0
181,24,36,9941321236,1,Subgroup P,0,2,11.37,7,107720.0,...,10.334783,10.867391,12.040217,6.033403,6.347014,6.512159,6.093082,6.504460,6.743331,0.0

In [100]:
year_1 = df_P_diabetes_1_2.loc[df_P_diabetes_1_2['analytic_period_id']==1][health_comparison_factors].reset_index(drop=True)
year_2 = df_P_diabetes_1_2.loc[df_P_diabetes_1_2['analytic_period_id']==2]['percentage_diff_absence'].reset_index(drop=True)

df_1_2 = year_1.merge(year_2, left_index=True, right_index=True,
                 how='outer', suffixes=('', '_y'))

df_1_2.drop(df_1_2.filter(regex='_y$').columns, axis=1, inplace=True)

df_1_2

,prog_1,prog_2,prog_3,prog_4,prog_5,prog_6,prog_7,prog_8,prog_9,prog_10,prog_11,prog_12,prog_13,prog_14,prog_15,prog_16,person_id,percentage_diff_absence
0,0,0,0,1,0,0,0,0,0,0,1,1,0,1,0,0,1503852073,21.0
1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1612242838,-83.0
2,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,1878767656,-92.0
3,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1958661151,0.0
4,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,2045103194,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,9429204609,6.0
65,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,9633517917,0.0
66,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,9708101272,0.0
67,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,9851594768,0.0
68,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,9941321236,0.0

In [101]:
counts = df_P_diabetes.groupby('person_id')['analytic_period_id'].unique()
person_ids_with_both_periods = [pid for pid, periods in counts.items() if 2 in periods and 3 in periods]

df_P_diabetes_2_3 = df_P_diabetes[df_P_diabetes['person_id'].isin(person_ids_with_both_periods)]
df_P_diabetes_2_3.reset_index(drop=True, inplace=True)
df_P_diabetes_2_3 = df_P_diabetes_2_3.loc[(df_P_diabetes_2_3['analytic_period_id']==2) | (df_P_diabetes_2_3['analytic_period_id']==3)]

df_P_diabetes_2_3

,ADI,Age,person_id,Gender,Subgroup,absence_indicator,analytic_period_id,tenure,overtime,salary,...,wildfire_potential_2018,wildfire_potential_2019,wildfire_potential_2019.1,wildfire_potential_ssp245_2025,wildfire_potential_ssp245_2035,wildfire_potential_ssp245_2045,wildfire_potential_ssp585_2025,wildfire_potential_ssp585_2035,wildfire_potential_ssp585_2045,percentage_diff_absence
0,26,57,1353615230,1,Subgroup P,0,2,30.55,1,139700.0,...,9.009783,10.081522,9.505435,6.542754,6.829352,6.997597,6.575143,7.011697,7.308716,0.0
1,26,58,1353615230,1,Subgroup P,0,3,31.56,1,143900.0,...,9.009783,10.081522,9.505435,6.542754,6.829352,6.997597,6.575143,7.011697,7.308716,0.0
2,28,35,1383777392,1,Subgroup P,26,2,4.23,1,92475.0,...,10.269565,10.132609,10.702174,6.123318,6.446156,6.621974,6.162228,6.574199,6.841721,0.0
3,28,36,1383777392,1,Subgroup P,0,3,5.23,1,95250.0,...,10.269565,10.132609,10.702174,6.123318,6.446156,6.621974,6.162228,6.574199,6.841721,26.0
5,32,33,1612242838,0,Subgroup P,110,2,11.62,1,54876.0,...,11.018478,11.153261,11.892391,6.069724,6.365864,6.512409,6.091926,6.469195,6.700504,-83.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170,26,40,9824418299,1,Subgroup P,0,3,8.29,3,93082.0,...,10.602174,10.189130,10.814130,6.346673,6.668234,6.856681,6.359701,6.796207,7.083618,0.0
172,33,41,9851594768,1,Subgroup P,0,2,18.83,7,92475.0,...,10.958696,11.210870,11.951087,6.064177,6.380910,6.548825,6.117186,6.522880,6.771772,0.0
173,33,42,9851594768,1,Subgroup P,0,3,19.84,7,95250.0,...,10.958696,11.210870,11.951087,6.064177,6.380910,6.548825,6.117186,6.522880,6.771772,0.0
175,24,36,9941321236,1,Subgroup P,0,2,11.37,7,107720.0,...,10.334783,10.867391,12.040217,6.033403,6.347014,6.512159,6.093082,6.504460,6.743331,0.0
176,21,37,9941321236,1,Subgroup P,0,3,12.38,5,110952.0,...,8.630435,8.752174,9.706522,5.509268,5.825750,6.010160,5.613933,6.039884,6.277661,0.0

In [102]:
year_2 = df_P_diabetes_2_3.loc[df_P_diabetes_2_3['analytic_period_id']==2][health_comparison_factors].reset_index(drop=True)
year_3 = df_P_diabetes_2_3.loc[df_P_diabetes_2_3['analytic_period_id']==3]['percentage_diff_absence'].reset_index(drop=True)

df_2_3 = year_2.merge(year_3, left_index=True, right_index=True,
                 how='outer', suffixes=('', '_y'))

df_2_3.drop(df_2_3.filter(regex='_y$').columns, axis=1, inplace=True)

df_2_3

,prog_1,prog_2,prog_3,prog_4,prog_5,prog_6,prog_7,prog_8,prog_9,prog_10,prog_11,prog_12,prog_13,prog_14,prog_15,prog_16,person_id,percentage_diff_absence
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1353615230,0.0
1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1383777392,26.0
2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1612242838,101.0
3,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,1878767656,92.0
4,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1955472534,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,9680028023,0.0
62,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,9708101272,0.0
63,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,9824418299,0.0
64,0,1,0,1,0,0,0,0,0,0,1,0,0,0,0,0,9851594768,0.0
65,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,9941321236,0.0

In [103]:
# train data: 2019 - 2018
# test data: 2020 - 2019

# get data from person_id with both analytic_period_id 1 and 2

from sklearn.model_selection import train_test_split

y_train = pd.DataFrame(df_1_2['percentage_diff_absence'])
y_train.loc[y_train['percentage_diff_absence'] > 0, 'percentage_diff_absence'] = np.log(y_train.loc[y_train['percentage_diff_absence'] > 0, 'percentage_diff_absence'])
y_train.loc[y_train['percentage_diff_absence'] < 0, 'percentage_diff_absence'] = -np.log(-y_train.loc[y_train['percentage_diff_absence'] < 0, 'percentage_diff_absence'])
x_train = pd.DataFrame(df_1_2[health_programs])
x_train[health_programs] = x_train[health_programs].astype('category')

y_test = pd.DataFrame(df_2_3['percentage_diff_absence'])
y_test.loc[y_test['percentage_diff_absence'] > 0, 'percentage_diff_absence'] = np.log(y_test.loc[y_test['percentage_diff_absence'] > 0, 'percentage_diff_absence'])
y_test.loc[y_test['percentage_diff_absence'] < 0, 'percentage_diff_absence'] = -np.log(-y_test.loc[y_test['percentage_diff_absence'] < 0, 'percentage_diff_absence'])
x_test = pd.DataFrame(df_2_3[health_programs])
x_test[health_programs] = x_test[health_programs].astype('category')

print("Train Set :", y_train.shape, x_train.shape)
print("Test Set  :", y_test.shape, x_test.shape)

Train Set : (69, 1) (69, 16)
Test Set  : (66, 1) (66, 16)

In [104]:
# use Linear Regression

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

linreg = LinearRegression()

linreg.fit(x_train, y_train)

print('Intercept of Regression \t: b = ', linreg.intercept_)

y_train_pred = linreg.predict(x_train)
y_test_pred = linreg.predict(x_test)

# Check the Goodness of Fit (on Train Data)
print("Goodness of Fit of Model \tTrain Dataset")
print("Explained Variance (R^2) \t:", linreg.score(x_train, y_train))
print("Mean Squared Error (MSE) \t:", mean_squared_error(y_train, y_train_pred))
print()

# Check the Goodness of Fit (on Test Data)
print("Goodness of Fit of Model \tTest Dataset")
print("Explained Variance (R^2) \t:", linreg.score(x_test, y_test))
print("Mean Squared Error (MSE) \t:", mean_squared_error(y_test, y_test_pred))
print()

Intercept of Regression 	: b =  [-0.15403271]
Goodness of Fit of Model 	Train Dataset
Explained Variance (R^2) 	: 0.11294778186627452
Mean Squared Error (MSE) 	: 2.0437658188128145

Goodness of Fit of Model 	Test Dataset
Explained Variance (R^2) 	: -0.09627312615605588
Mean Squared Error (MSE) 	: 3.5235603784903256

In [105]:
import statsmodels.api as sm

x_train_with_constant = sm.add_constant(x_train)
model = sm.OLS(y_train, x_train_with_constant)
result = model.fit()

print(result.summary())

                               OLS Regression Results
===================================================================================
Dep. Variable:     percentage_diff_absence   R-squared:                       0.113
Model:                                 OLS   Adj. R-squared:                 -0.022
Method:                      Least Squares   F-statistic:                    0.8347
Date:                     Sat, 06 Apr 2024   Prob (F-statistic):              0.587
Time:                             16:55:03   Log-Likelihood:                -122.57
No. Observations:                       69   AIC:                             265.1
Df Residuals:                           59   BIC:                             287.5
Df Model:                                9
Covariance Type:                 nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         -0.1540      0.515     -0.299      0.766      -1.185       0.877
prog_1         0.2720      0.668      0.407      0.685      -1.065       1.609
prog_2         0.3251      1.595      0.204      0.839      -2.867       3.517
prog_3     -9.063e-16   4.44e-16     -2.040      0.046    -1.8e-15   -1.73e-17
prog_4        -0.0851      0.460     -0.185      0.854      -1.006       0.836
prog_5         1.2487      0.864      1.445      0.154      -0.480       2.978
prog_6         0.1040      1.170      0.089      0.929      -2.238       2.446
prog_7     -1.068e-15   5.93e-16     -1.802      0.077   -2.25e-15    1.18e-16
prog_8      4.187e-16   2.66e-16      1.575      0.121   -1.13e-16     9.5e-16
prog_9      1.935e-17   3.58e-16      0.054      0.957   -6.98e-16    7.37e-16
prog_10             0          0        nan        nan           0           0
prog_11       -0.0860      0.587     -0.146      0.884      -1.261       1.089
prog_12        0.7773      0.694      1.120      0.267      -0.611       2.166
prog_13        3.0126      1.571      1.917      0.060      -0.132       6.157
prog_14       -0.6799      0.692     -0.983      0.330      -2.065       0.705
prog_15             0          0        nan        nan           0           0
prog_16             0          0        nan        nan           0           0
==============================================================================
Omnibus:                       13.254   Durbin-Watson:                   1.891
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               31.948
Skew:                          -0.465   Prob(JB):                     1.15e-07
Kurtosis:                       6.201   Cond. No.                          inf
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is      0. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

C:\Users\Willis\anaconda3\Lib\site-packages\statsmodels\regression\linear_model.py:1965: RuntimeWarning: divide by zero encountered in scalar divide
  return np.sqrt(eigvals[0]/eigvals[-1])

In [106]:
# use decision tree regressor

from sklearn.tree import DecisionTreeRegressor

decisiontreemodel = DecisionTreeRegressor(max_depth=3)
result = decisiontreemodel.fit(x_train, y_train)

y_train_pred = decisiontreemodel.predict(x_train)
train_mse = mean_squared_error(y_train_pred, y_train)
y_test_pred = decisiontreemodel.predict(x_test)
test_mse = mean_squared_error(y_test_pred, y_test)

print("Mean Squared Error (Train Dataset):", train_mse)
print("Mean Squared Error (Test Dataset):", test_mse)

Mean Squared Error (Train Dataset): 2.0063914256951496
Mean Squared Error (Test Dataset): 3.6518399585578205

In [107]:
from sklearn.model_selection import GridSearchCV

param_grid = {'max_depth': range(1, 11)}

decisiontreemodel = DecisionTreeRegressor()

grid_search = GridSearchCV(estimator=decisiontreemodel, param_grid=param_grid, cv=5)

grid_search.fit(x_train, y_train)
best_max_depth = grid_search.best_params_['max_depth']

print("Best max_depth:", best_max_depth)

Best max_depth: 1

In [108]:
# use decision tree regressor

from sklearn.tree import DecisionTreeRegressor

decisiontreemodel = DecisionTreeRegressor(max_depth=1)
result = decisiontreemodel.fit(x_train, y_train)

y_train_pred = decisiontreemodel.predict(x_train)
train_mse = mean_squared_error(y_train_pred, y_train)
y_test_pred = decisiontreemodel.predict(x_test)
test_mse = mean_squared_error(y_test_pred, y_test)

print("Mean Squared Error (Train Dataset):", train_mse)
print("Mean Squared Error (Test Dataset):", test_mse)

Mean Squared Error (Train Dataset): 2.181936532948909
Mean Squared Error (Test Dataset): 3.2852672281640576

In [109]:
significant_variable = {}
significant_variable['significant_variables'] = []
fr = decisiontreemodel.feature_importances_ 
importance_dict = dict(zip(x_train.columns, fr))
for key in importance_dict:
    if importance_dict[key] > 0:
        significant_variable['significant_variables'].append(key)
        
print(significant_variable)

{'significant_variables': ['prog_13']}

In [110]:
from sklearn.ensemble import RandomForestRegressor

randomforest = RandomForestRegressor(n_estimators=100, max_depth=5, random_state=42)
randomforest.fit(x_train, y_train)

y_train_pred = randomforest.predict(x_train)
train_mse = mean_squared_error(y_train_pred, y_train)
y_test_pred = randomforest.predict(x_test)
test_mse = mean_squared_error(y_test_pred, y_test)

print("Mean Squared Error (Train Dataset):", train_mse)
print("Mean Squared Error (Test Dataset):", test_mse)

Mean Squared Error (Train Dataset): 1.6361775538709444
Mean Squared Error (Test Dataset): 5.23558140311574

C:\Users\Willis\AppData\Local\Temp\ipykernel_26140\458196643.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  randomforest.fit(x_train, y_train)

In [111]:
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint

param_dist = {
    'n_estimators': randint(50, 200),
    'max_depth': [None] + list(range(5, 20)),
    'min_samples_split': randint(2, 20)
}

randomized_search = RandomizedSearchCV(estimator=RandomForestRegressor(), param_distributions=param_dist, n_iter=5, cv=5, scoring='neg_mean_squared_error', random_state=42)

randomized_search.fit(x_train, y_train)

best_params = randomized_search.best_params_
print(best_params)

C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)

{'max_depth': 6, 'min_samples_split': 12, 'n_estimators': 137}

C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:909: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self.best_estimator_.fit(X, y, **fit_params)

In [112]:
randomforest = RandomForestRegressor(n_estimators=best_params['n_estimators'], max_depth=best_params['max_depth'], min_samples_split=best_params['min_samples_split'], random_state=42)
randomforest.fit(x_train, y_train)

y_train_pred = randomforest.predict(x_train)
train_mse = mean_squared_error(y_train_pred, y_train)
y_test_pred = randomforest.predict(x_test)
test_mse = mean_squared_error(y_test_pred, y_test)

print("Mean Squared Error (Train Dataset):", train_mse)
print("Mean Squared Error (Test Dataset):", test_mse)

Mean Squared Error (Train Dataset): 2.001003274443115
Mean Squared Error (Test Dataset): 3.862768465825327

C:\Users\Willis\AppData\Local\Temp\ipykernel_26140\3010193299.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  randomforest.fit(x_train, y_train)

In [113]:
feature_importances = randomforest.feature_importances_
feature_importance_dict = dict(zip(x_train.columns, feature_importances))
sorted_features = sorted(feature_importance_dict.items(), key=lambda x: x[1], reverse=True)

sorted_features

[('prog_14', 0.44485252880765985),
 ('prog_13', 0.2179755182826518),
 ('prog_5', 0.13926332016954956),
 ('prog_12', 0.09064221163972133),
 ('prog_4', 0.06556231010492257),
 ('prog_11', 0.024471879063626533),
 ('prog_1', 0.011732073665131605),
 ('prog_6', 0.004185220686498279),
 ('prog_2', 0.0013149375802384445),
 ('prog_3', 0.0),
 ('prog_7', 0.0),
 ('prog_8', 0.0),
 ('prog_9', 0.0),
 ('prog_10', 0.0),
 ('prog_15', 0.0),
 ('prog_16', 0.0)]

#### combined

In [164]:
# change 0 and 1

df_P_combined = df_P.loc[(df_P['cc_mskChronic'] == 1) & 
                           (df_P['cc_diabetes'] == 1) & 
                           (df_P['cc_cardiac'] == 1)].reset_index(drop=True)

df_P_combined = df_P_combined.sort_values(by=['person_id', 'analytic_period_id'])

df_P_combined['percentage_diff_absence'] = round((df_P_combined.groupby('person_id')['absence_indicator'].diff() * -1),0)
df_P_combined['percentage_diff_absence'] = df_P_combined['percentage_diff_absence'].fillna(0)
df_P_combined['percentage_diff_absence'] = np.where(df_P_combined['percentage_diff_absence']== -0, 0, df_P_combined['percentage_diff_absence'])
df_P_combined[health_programs] = np.where(df_P_combined[health_programs] == -1, 0, df_P_combined[health_programs])

df_P_combined

,ADI,Age,person_id,Gender,Subgroup,absence_indicator,analytic_period_id,tenure,overtime,salary,...,wildfire_potential_2018,wildfire_potential_2019,wildfire_potential_2019.1,wildfire_potential_ssp245_2025,wildfire_potential_ssp245_2035,wildfire_potential_ssp245_2045,wildfire_potential_ssp585_2025,wildfire_potential_ssp585_2035,wildfire_potential_ssp585_2045,percentage_diff_absence
0,36,56,1018774502,1,Subgroup P,106,3,8.61,1,67321.0,...,11.039130,11.023913,11.963043,6.069724,6.365864,6.512409,6.091926,6.469195,6.700504,0.0
1,31,45,1067000561,1,Subgroup P,0,1,19.62,3,130200.0,...,9.286957,9.943478,10.203261,6.571641,6.881262,7.077469,6.625778,7.091410,7.391057,0.0
2,31,46,1067000561,1,Subgroup P,0,2,20.62,3,141000.0,...,9.286957,9.943478,10.203261,6.571641,6.881262,7.077469,6.625778,7.091410,7.391057,0.0
3,31,47,1067000561,1,Subgroup P,0,3,21.62,1,142500.0,...,9.286957,9.943478,10.203261,6.571641,6.881262,7.077469,6.625778,7.091410,7.391057,0.0
4,24,53,1113678438,1,Subgroup P,0,1,21.86,7,102329.0,...,8.896739,9.940217,9.573913,6.542754,6.829352,6.997597,6.575143,7.011697,7.308716,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
465,10,67,9817720279,1,Subgroup P,28,2,9.78,5,82218.0,...,9.845652,10.602174,11.725000,5.881690,6.203235,6.383163,5.963483,6.392136,6.643947,0.0
466,10,68,9817720279,1,Subgroup P,25,3,10.43,3,82218.0,...,9.845652,10.602174,11.725000,5.881690,6.203235,6.383163,5.963483,6.392136,6.643947,3.0
467,26,56,9869420037,1,Subgroup P,0,2,14.22,3,107720.0,...,10.870652,11.036957,11.828261,6.064177,6.380910,6.548825,6.117186,6.522880,6.771772,0.0
468,13,43,9941002089,1,Subgroup P,0,2,16.47,7,97346.0,...,11.201087,11.230435,11.883696,6.069724,6.365864,6.512409,6.091926,6.469195,6.700504,0.0
469,13,44,9941002089,1,Subgroup P,44,3,17.47,5,109098.0,...,11.201087,11.230435,11.883696,6.069724,6.365864,6.512409,6.091926,6.469195,6.700504,-44.0

In [165]:
counts = df_P_combined.groupby('person_id')['analytic_period_id'].unique()
person_ids_with_both_periods = [pid for pid, periods in counts.items() if 1 in periods and 2 in periods]

df_P_combined_1_2 = df_P_combined[df_P_combined['person_id'].isin(person_ids_with_both_periods)]
df_P_combined_1_2.reset_index(drop=True, inplace=True)
df_P_combined_1_2 = df_P_combined_1_2.loc[(df_P_combined_1_2['analytic_period_id']==1) | (df_P_combined_1_2['analytic_period_id']==2)]

df_P_combined_1_2

,ADI,Age,person_id,Gender,Subgroup,absence_indicator,analytic_period_id,tenure,overtime,salary,...,wildfire_potential_2018,wildfire_potential_2019,wildfire_potential_2019.1,wildfire_potential_ssp245_2025,wildfire_potential_ssp245_2035,wildfire_potential_ssp245_2045,wildfire_potential_ssp585_2025,wildfire_potential_ssp585_2035,wildfire_potential_ssp585_2045,percentage_diff_absence
0,31,45,1067000561,1,Subgroup P,0,1,19.62,3,130200.0,...,9.286957,9.943478,10.203261,6.571641,6.881262,7.077469,6.625778,7.091410,7.391057,0.0
1,31,46,1067000561,1,Subgroup P,0,2,20.62,3,141000.0,...,9.286957,9.943478,10.203261,6.571641,6.881262,7.077469,6.625778,7.091410,7.391057,0.0
3,24,53,1113678438,1,Subgroup P,0,1,21.86,7,102329.0,...,8.896739,9.940217,9.573913,6.542754,6.829352,6.997597,6.575143,7.011697,7.308716,0.0
4,24,54,1113678438,1,Subgroup P,0,2,22.87,9,105400.0,...,8.896739,9.940217,9.573913,6.542754,6.829352,6.997597,6.575143,7.011697,7.308716,0.0
6,19,69,1339066557,0,Subgroup P,0,1,50.55,0,76200.0,...,10.005435,9.830435,10.272826,5.940742,6.211470,6.337823,5.921674,6.253634,6.474338,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
204,28,60,9549054157,1,Subgroup P,0,2,21.54,1,118200.0,...,10.372826,10.489130,11.231522,6.064177,6.380910,6.548825,6.117186,6.522880,6.771772,0.0
206,27,54,9633759463,0,Subgroup P,0,1,31.63,1,109800.0,...,10.901087,11.234783,12.113043,6.064177,6.380910,6.548825,6.117186,6.522880,6.771772,0.0
207,27,55,9633759463,0,Subgroup P,6,2,32.63,1,113100.0,...,10.901087,11.234783,12.113043,6.064177,6.380910,6.548825,6.117186,6.522880,6.771772,-6.0
209,21,49,9774315020,1,Subgroup P,0,1,16.70,5,87738.0,...,9.326087,9.703261,10.839130,5.881690,6.203235,6.383163,5.963483,6.392136,6.643947,0.0
210,18,50,9774315020,1,Subgroup P,217,2,17.70,3,90370.0,...,9.397826,9.616304,10.700000,5.881690,6.203235,6.383163,5.963483,6.392136,6.643947,-217.0

In [166]:
year_1 = df_P_combined_1_2.loc[df_P_combined_1_2['analytic_period_id']==1][health_comparison_factors].reset_index(drop=True)
year_2 = df_P_combined_1_2.loc[df_P_combined_1_2['analytic_period_id']==2]['percentage_diff_absence'].reset_index(drop=True)

df_1_2 = year_1.merge(year_2, left_index=True, right_index=True,
                 how='outer', suffixes=('', '_y'))

df_1_2.drop(df_1_2.filter(regex='_y$').columns, axis=1, inplace=True)

df_1_2

,prog_1,prog_2,prog_3,prog_4,prog_5,prog_6,prog_7,prog_8,prog_9,prog_10,prog_11,prog_12,prog_13,prog_14,prog_15,prog_16,person_id,percentage_diff_absence
0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1067000561,0.0
1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1113678438,0.0
2,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1339066557,0.0
3,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1439762767,0.0
4,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1467008558,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,9229818761,0.0
68,0,0,0,1,0,0,0,0,0,0,1,0,0,1,0,0,9358878049,0.0
69,0,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,9549054157,0.0
70,0,0,0,1,0,0,0,0,0,0,1,0,0,1,0,0,9633759463,-6.0
71,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,9774315020,-217.0

In [167]:
counts = df_P_combined.groupby('person_id')['analytic_period_id'].unique()
person_ids_with_both_periods = [pid for pid, periods in counts.items() if 2 in periods and 3 in periods]

df_P_combined_2_3 = df_P_combined[df_P_combined['person_id'].isin(person_ids_with_both_periods)]
df_P_combined_2_3.reset_index(drop=True, inplace=True)
df_P_combined_2_3 = df_P_combined_2_3.loc[(df_P_combined_2_3['analytic_period_id']==2) | (df_P_combined_2_3['analytic_period_id']==3)]

df_P_combined_2_3

,ADI,Age,person_id,Gender,Subgroup,absence_indicator,analytic_period_id,tenure,overtime,salary,...,wildfire_potential_2018,wildfire_potential_2019,wildfire_potential_2019.1,wildfire_potential_ssp245_2025,wildfire_potential_ssp245_2035,wildfire_potential_ssp245_2045,wildfire_potential_ssp585_2025,wildfire_potential_ssp585_2035,wildfire_potential_ssp585_2045,percentage_diff_absence
1,31,46,1067000561,1,Subgroup P,0,2,20.62,3,141000.0,...,9.286957,9.943478,10.203261,6.571641,6.881262,7.077469,6.625778,7.091410,7.391057,0.0
2,31,47,1067000561,1,Subgroup P,0,3,21.62,1,142500.0,...,9.286957,9.943478,10.203261,6.571641,6.881262,7.077469,6.625778,7.091410,7.391057,0.0
4,24,54,1113678438,1,Subgroup P,0,2,22.87,9,105400.0,...,8.896739,9.940217,9.573913,6.542754,6.829352,6.997597,6.575143,7.011697,7.308716,0.0
5,24,55,1113678438,1,Subgroup P,86,3,23.87,5,108564.0,...,8.896739,9.940217,9.573913,6.542754,6.829352,6.997597,6.575143,7.011697,7.308716,-86.0
6,39,59,1148076844,1,Subgroup P,32,2,5.19,1,95900.0,...,10.118478,10.333696,10.833696,6.566475,6.882546,7.078842,6.570887,7.018056,7.308116,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
337,18,51,9774315020,1,Subgroup P,240,3,18.70,5,93082.0,...,9.397826,9.616304,10.700000,5.881690,6.203235,6.383163,5.963483,6.392136,6.643947,-23.0
338,10,67,9817720279,1,Subgroup P,28,2,9.78,5,82218.0,...,9.845652,10.602174,11.725000,5.881690,6.203235,6.383163,5.963483,6.392136,6.643947,0.0
339,10,68,9817720279,1,Subgroup P,25,3,10.43,3,82218.0,...,9.845652,10.602174,11.725000,5.881690,6.203235,6.383163,5.963483,6.392136,6.643947,3.0
340,13,43,9941002089,1,Subgroup P,0,2,16.47,7,97346.0,...,11.201087,11.230435,11.883696,6.069724,6.365864,6.512409,6.091926,6.469195,6.700504,0.0
341,13,44,9941002089,1,Subgroup P,44,3,17.47,5,109098.0,...,11.201087,11.230435,11.883696,6.069724,6.365864,6.512409,6.091926,6.469195,6.700504,-44.0

In [168]:
year_2 = df_P_combined_2_3.loc[df_P_combined_2_3['analytic_period_id']==2][health_comparison_factors].reset_index(drop=True)
year_3 = df_P_combined_2_3.loc[df_P_combined_2_3['analytic_period_id']==3]['percentage_diff_absence'].reset_index(drop=True)

df_2_3 = year_2.merge(year_3, left_index=True, right_index=True,
                 how='outer', suffixes=('', '_y'))

df_2_3.drop(df_2_3.filter(regex='_y$').columns, axis=1, inplace=True)

df_2_3

,prog_1,prog_2,prog_3,prog_4,prog_5,prog_6,prog_7,prog_8,prog_9,prog_10,prog_11,prog_12,prog_13,prog_14,prog_15,prog_16,person_id,percentage_diff_absence
0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1067000561,0.0
1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1113678438,-86.0
2,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1148076844,21.0
3,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,1265342295,1.0
4,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1339066557,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,9743206599,0.0
133,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,9763140503,0.0
134,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,9774315020,-23.0
135,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,9817720279,3.0
136,1,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,9941002089,-44.0

In [169]:
# train data: 2019 - 2018
# test data: 2020 - 2019

# get data from person_id with both analytic_period_id 1 and 2

from sklearn.model_selection import train_test_split

y_train = pd.DataFrame(df_1_2['percentage_diff_absence'])
y_train.loc[y_train['percentage_diff_absence'] > 0, 'percentage_diff_absence'] = np.log(y_train.loc[y_train['percentage_diff_absence'] > 0, 'percentage_diff_absence'])
y_train.loc[y_train['percentage_diff_absence'] < 0, 'percentage_diff_absence'] = -np.log(-y_train.loc[y_train['percentage_diff_absence'] < 0, 'percentage_diff_absence'])
x_train = pd.DataFrame(df_1_2[health_programs])
x_train[health_programs] = x_train[health_programs].astype('category')

y_test = pd.DataFrame(df_2_3['percentage_diff_absence'])
y_test.loc[y_test['percentage_diff_absence'] > 0, 'percentage_diff_absence'] = np.log(y_test.loc[y_test['percentage_diff_absence'] > 0, 'percentage_diff_absence'])
y_test.loc[y_test['percentage_diff_absence'] < 0, 'percentage_diff_absence'] = -np.log(-y_test.loc[y_test['percentage_diff_absence'] < 0, 'percentage_diff_absence'])
x_test = pd.DataFrame(df_2_3[health_programs])
x_test[health_programs] = x_test[health_programs].astype('category')

print("Train Set :", y_train.shape, x_train.shape)
print("Test Set  :", y_test.shape, x_test.shape)

Train Set : (72, 1) (72, 16)
Test Set  : (137, 1) (137, 16)

In [170]:
# use Linear Regression

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

linreg = LinearRegression()

linreg.fit(x_train, y_train)

print('Intercept of Regression \t: b = ', linreg.intercept_)

y_train_pred = linreg.predict(x_train)
y_test_pred = linreg.predict(x_test)

# Check the Goodness of Fit (on Train Data)
print("Goodness of Fit of Model \tTrain Dataset")
print("Explained Variance (R^2) \t:", linreg.score(x_train, y_train))
print("Mean Squared Error (MSE) \t:", mean_squared_error(y_train, y_train_pred))
print()

# Check the Goodness of Fit (on Test Data)
print("Goodness of Fit of Model \tTest Dataset")
print("Explained Variance (R^2) \t:", linreg.score(x_test, y_test))
print("Mean Squared Error (MSE) \t:", mean_squared_error(y_test, y_test_pred))
print()

Intercept of Regression 	: b =  [0.79257151]
Goodness of Fit of Model 	Train Dataset
Explained Variance (R^2) 	: 0.11580021375732197
Mean Squared Error (MSE) 	: 6.005885224537802

Goodness of Fit of Model 	Test Dataset
Explained Variance (R^2) 	: -0.13692053225714118
Mean Squared Error (MSE) 	: 5.941468508074329

In [171]:
import statsmodels.api as sm

x_train_with_constant = sm.add_constant(x_train)
model = sm.OLS(y_train, x_train_with_constant)
result = model.fit()

print(result.summary())

                               OLS Regression Results
===================================================================================
Dep. Variable:     percentage_diff_absence   R-squared:                       0.116
Model:                                 OLS   Adj. R-squared:                 -0.013
Method:                      Least Squares   F-statistic:                    0.9022
Date:                     Sat, 06 Apr 2024   Prob (F-statistic):              0.529
Time:                             19:17:58   Log-Likelihood:                -166.70
No. Observations:                       72   AIC:                             353.4
Df Residuals:                           62   BIC:                             376.2
Df Model:                                9
Covariance Type:                 nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.7926      0.803      0.987      0.327      -0.812       2.397
prog_1         1.6252      3.013      0.539      0.592      -4.397       7.648
prog_2         1.3151      1.317      0.998      0.322      -1.318       3.948
prog_3      1.478e-15   1.51e-15      0.977      0.332   -1.55e-15     4.5e-15
prog_4        -0.3085      0.894     -0.345      0.731      -2.095       1.478
prog_5        -2.0163      1.259     -1.601      0.114      -4.533       0.501
prog_6         1.8015      1.940      0.929      0.357      -2.076       5.679
prog_7     -3.653e-16   2.79e-16     -1.310      0.195   -9.23e-16    1.92e-16
prog_8     -8.148e-17   7.22e-16     -0.113      0.911   -1.53e-15    1.36e-15
prog_9      3.058e-16   4.84e-16      0.631      0.530   -6.62e-16    1.27e-15
prog_10             0          0        nan        nan           0           0
prog_11       -0.6480      0.912     -0.711      0.480      -2.471       1.175
prog_12       -1.3811      1.114     -1.240      0.220      -3.608       0.846
prog_13       -2.1572      1.921     -1.123      0.266      -5.997       1.682
prog_14        0.5551      0.993      0.559      0.578      -1.430       2.541
prog_15             0          0        nan        nan           0           0
prog_16             0          0        nan        nan           0           0
==============================================================================
Omnibus:                        2.030   Durbin-Watson:                   1.543
Prob(Omnibus):                  0.362   Jarque-Bera (JB):                1.485
Skew:                          -0.135   Prob(JB):                        0.476
Kurtosis:                       2.351   Cond. No.                          inf
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is      0. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

C:\Users\Willis\anaconda3\Lib\site-packages\statsmodels\regression\linear_model.py:1965: RuntimeWarning: divide by zero encountered in scalar divide
  return np.sqrt(eigvals[0]/eigvals[-1])

In [172]:
# use decision tree regressor

from sklearn.tree import DecisionTreeRegressor

decisiontreemodel = DecisionTreeRegressor(max_depth=3)
result = decisiontreemodel.fit(x_train, y_train)

y_train_pred = decisiontreemodel.predict(x_train)
train_mse = mean_squared_error(y_train_pred, y_train)
y_test_pred = decisiontreemodel.predict(x_test)
test_mse = mean_squared_error(y_test_pred, y_test)

print("Mean Squared Error (Train Dataset):", train_mse)
print("Mean Squared Error (Test Dataset):", test_mse)

Mean Squared Error (Train Dataset): 5.783658703761684
Mean Squared Error (Test Dataset): 6.263489959165422

In [173]:
from sklearn.model_selection import GridSearchCV

param_grid = {'max_depth': range(1, 11)}

decisiontreemodel = DecisionTreeRegressor()

grid_search = GridSearchCV(estimator=decisiontreemodel, param_grid=param_grid, cv=5)

grid_search.fit(x_train, y_train)
best_max_depth = grid_search.best_params_['max_depth']

print("Best max_depth:", best_max_depth)

Best max_depth: 1

In [174]:
# use decision tree regressor

from sklearn.tree import DecisionTreeRegressor

decisiontreemodel = DecisionTreeRegressor(max_depth=best_max_depth)
result = decisiontreemodel.fit(x_train, y_train)

y_train_pred = decisiontreemodel.predict(x_train)
train_mse = mean_squared_error(y_train_pred, y_train)
y_test_pred = decisiontreemodel.predict(x_test)
test_mse = mean_squared_error(y_test_pred, y_test)

print("Mean Squared Error (Train Dataset):", train_mse)
print("Mean Squared Error (Test Dataset):", test_mse)

Mean Squared Error (Train Dataset): 6.5501799610284746
Mean Squared Error (Test Dataset): 5.206588904189917

In [175]:
significant_variable = {}
significant_variable['significant_variables'] = []
fr = decisiontreemodel.feature_importances_ 
importance_dict = dict(zip(x_train.columns, fr))
for key in importance_dict:
    if importance_dict[key] > 0:
        significant_variable['significant_variables'].append(key)
        
print(significant_variable)

{'significant_variables': ['prog_5']}

In [176]:
from sklearn.ensemble import RandomForestRegressor

randomforest = RandomForestRegressor(n_estimators=100, max_depth=5, random_state=42)
randomforest.fit(x_train, y_train)

y_train_pred = randomforest.predict(x_train)
train_mse = mean_squared_error(y_train_pred, y_train)
y_test_pred = randomforest.predict(x_test)
test_mse = mean_squared_error(y_test_pred, y_test)

print("Mean Squared Error (Train Dataset):", train_mse)
print("Mean Squared Error (Test Dataset):", test_mse)

Mean Squared Error (Train Dataset): 4.948411791406752
Mean Squared Error (Test Dataset): 6.476118985509096

C:\Users\Willis\AppData\Local\Temp\ipykernel_26140\458196643.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  randomforest.fit(x_train, y_train)

In [177]:
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint

param_dist = {
    'n_estimators': randint(50, 200),
    'max_depth': [None] + list(range(5, 20)),
    'min_samples_split': randint(2, 20)
}

randomized_search = RandomizedSearchCV(estimator=RandomForestRegressor(), param_distributions=param_dist, n_iter=5, cv=5, scoring='neg_mean_squared_error', random_state=42)

randomized_search.fit(x_train, y_train)

best_params = randomized_search.best_params_
print(best_params)

C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)

{'max_depth': 6, 'min_samples_split': 12, 'n_estimators': 137}

C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:909: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self.best_estimator_.fit(X, y, **fit_params)

In [178]:
randomforest = RandomForestRegressor(n_estimators=best_params['n_estimators'], max_depth=best_params['max_depth'], min_samples_split=best_params['min_samples_split'], random_state=42)
randomforest.fit(x_train, y_train)

y_train_pred = randomforest.predict(x_train)
train_mse = mean_squared_error(y_train_pred, y_train)
y_test_pred = randomforest.predict(x_test)
test_mse = mean_squared_error(y_test_pred, y_test)

print("Mean Squared Error (Train Dataset):", train_mse)
print("Mean Squared Error (Test Dataset):", test_mse)

Mean Squared Error (Train Dataset): 5.585810075045156
Mean Squared Error (Test Dataset): 5.994439031747768

C:\Users\Willis\AppData\Local\Temp\ipykernel_26140\3010193299.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  randomforest.fit(x_train, y_train)

In [179]:
feature_importances = randomforest.feature_importances_
feature_importance_dict = dict(zip(x_train.columns, feature_importances))
sorted_features = sorted(feature_importance_dict.items(), key=lambda x: x[1], reverse=True)

sorted_features

[('prog_5', 0.2607548878813489),
 ('prog_2', 0.1544792775398865),
 ('prog_4', 0.14696171516434361),
 ('prog_14', 0.12064442893088062),
 ('prog_12', 0.1017343674358286),
 ('prog_6', 0.07803634197923691),
 ('prog_13', 0.07698556854923687),
 ('prog_11', 0.06040341251923793),
 ('prog_1', 0.0),
 ('prog_3', 0.0),
 ('prog_7', 0.0),
 ('prog_8', 0.0),
 ('prog_9', 0.0),
 ('prog_10', 0.0),
 ('prog_15', 0.0),
 ('prog_16', 0.0)]

### Subgroup C

In [276]:
df_C_depression = df_C.loc[(df_C['cc_depression'] == 1) & 
                           (df_C['cc_RespiratorySinusAllergy_chronic'] == 1) & 
                           (df_C['cc_cardiac'] == 1)].reset_index(drop=True)

df_C_depression = df_C_depression.sort_values(by=['person_id', 'analytic_period_id'])

df_C_depression['percentage_diff_absence'] = round((df_C_depression.groupby('person_id')['absence_indicator'].diff() * -1),0)
df_C_depression['percentage_diff_absence'] = df_C_depression['percentage_diff_absence'].fillna(0)
df_C_depression['percentage_diff_absence'] = np.where(df_C_depression['percentage_diff_absence']== -0, 0, df_C_depression['percentage_diff_absence'])
df_C_depression[health_programs] = np.where(df_C_depression[health_programs] == -1, 0, df_C_depression[health_programs])

df_C_depression

,ADI,Age,person_id,Gender,Subgroup,absence_indicator,analytic_period_id,tenure,overtime,salary,...,wildfire_potential_2018,wildfire_potential_2019,wildfire_potential_2019.1,wildfire_potential_ssp245_2025,wildfire_potential_ssp245_2035,wildfire_potential_ssp245_2045,wildfire_potential_ssp585_2025,wildfire_potential_ssp585_2035,wildfire_potential_ssp585_2045,percentage_diff_absence
0,56,54,1079904645,0,Subgroup C,7,3,9.713348,1,35020.00,...,8.461957,7.867391,9.941304,6.438193,6.942547,7.145548,6.525085,7.158397,7.664034,0.0
1,80,49,1094883842,0,Subgroup C,0,2,31.251798,1,64418.00,...,18.093478,18.466304,16.157609,11.592954,11.850834,11.837443,11.439993,11.784370,12.120530,0.0
2,80,50,1094883842,0,Subgroup C,0,3,32.251798,1,64418.00,...,18.093478,18.466304,16.157609,11.592954,11.850834,11.837443,11.439993,11.784370,12.120530,0.0
3,55,60,1216979791,1,Subgroup C,0,1,11.469756,1,34236.00,...,7.625000,7.289130,9.463043,7.290190,7.820141,8.152020,7.299540,7.878583,8.454539,0.0
4,55,61,1216979791,1,Subgroup C,0,2,12.469756,1,35204.39,...,7.625000,7.289130,9.463043,7.290190,7.820141,8.152020,7.299540,7.878583,8.454539,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131,42,63,9513120749,0,Subgroup C,0,2,15.862023,1,66228.46,...,9.798913,9.890217,11.740217,6.003101,6.479834,6.712516,6.082930,6.744432,7.322138,0.0
132,62,29,9578749883,0,Subgroup C,0,3,8.505931,1,64418.00,...,8.529348,8.061957,9.997826,6.476331,6.974277,7.171684,6.556868,7.189641,7.705541,0.0
133,38,39,9585888304,0,Subgroup C,0,3,16.555378,1,55680.23,...,9.508696,9.765217,11.720652,6.003201,6.482577,6.724924,6.080874,6.738228,7.317786,0.0
134,55,49,9589944281,0,Subgroup C,0,3,16.900354,1,64418.00,...,13.177174,8.913043,10.466304,7.931101,8.381245,8.578490,8.111887,8.596949,9.243535,0.0
135,79,51,9660914135,0,Subgroup C,61,2,22.646557,1,62410.06,...,9.856522,9.865217,11.760870,6.010345,6.469191,6.710849,6.100414,6.761607,7.342828,0.0

In [277]:
counts = df_C_depression.groupby('person_id')['analytic_period_id'].unique()
person_ids_with_both_periods = [pid for pid, periods in counts.items() if 1 in periods and 2 in periods]

df_C_depression_1_2 = df_C_depression[df_C_depression['person_id'].isin(person_ids_with_both_periods)]
df_C_depression_1_2.reset_index(drop=True, inplace=True)
df_C_depression_1_2 = df_C_depression_1_2.loc[(df_C_depression_1_2['analytic_period_id']==1) | (df_C_depression_1_2['analytic_period_id']==2)]

df_C_depression_1_2

,ADI,Age,person_id,Gender,Subgroup,absence_indicator,analytic_period_id,tenure,overtime,salary,...,wildfire_potential_2018,wildfire_potential_2019,wildfire_potential_2019.1,wildfire_potential_ssp245_2025,wildfire_potential_ssp245_2035,wildfire_potential_ssp245_2045,wildfire_potential_ssp585_2025,wildfire_potential_ssp585_2035,wildfire_potential_ssp585_2045,percentage_diff_absence
0,55,60,1216979791,1,Subgroup C,0,1,11.469756,1,34236.00,...,7.625000,7.289130,9.463043,7.290190,7.820141,8.152020,7.299540,7.878583,8.454539,0.0
1,55,61,1216979791,1,Subgroup C,0,2,12.469756,1,35204.39,...,7.625000,7.289130,9.463043,7.290190,7.820141,8.152020,7.299540,7.878583,8.454539,0.0
2,0,55,1503980266,0,Subgroup C,0,1,12.140544,1,64418.00,...,14.318478,12.981522,15.590217,8.804982,8.961899,9.141830,8.781430,9.067994,9.285485,0.0
3,4,56,1503980266,0,Subgroup C,0,2,13.140544,1,64418.00,...,3.848913,4.498913,5.517391,6.656552,6.736435,6.843538,6.623965,6.810580,6.960196,0.0
5,50,63,1712582566,1,Subgroup C,0,1,14.689535,1,24828.00,...,10.520652,11.139130,10.727174,5.553928,5.753603,5.731946,5.679374,5.835318,6.254604,0.0
6,50,64,1712582566,1,Subgroup C,0,2,15.689535,1,25510.27,...,10.520652,11.139130,10.727174,5.553928,5.753603,5.731946,5.679374,5.835318,6.254604,0.0
7,85,67,2343841964,0,Subgroup C,0,1,13.482118,1,64418.00,...,22.534783,19.705435,20.473913,15.904061,16.271042,16.380516,15.572548,16.111680,16.738945,0.0
8,85,68,2343841964,0,Subgroup C,79,2,14.482118,1,64418.00,...,22.534783,19.705435,20.473913,15.904061,16.271042,16.380516,15.572548,16.111680,16.738945,-79.0
9,64,45,2432263119,0,Subgroup C,0,1,6.141789,1,95000.00,...,31.029348,31.791304,34.463043,25.898552,26.188574,26.471987,25.735262,26.428740,27.669125,0.0
10,64,46,2432263119,0,Subgroup C,0,2,7.141789,1,96900.00,...,31.029348,31.791304,34.463043,25.898552,26.188574,26.471987,25.735262,26.428740,27.669125,0.0
12,80,33,2824773588,0,Subgroup C,0,1,7.157553,1,56005.00,...,9.486957,9.622826,11.872826,5.928487,6.382446,6.627354,6.013501,6.662659,7.239450,0.0
13,80,34,2824773588,0,Subgroup C,0,2,8.157553,1,56005.00,...,9.486957,9.622826,11.872826,5.928487,6.382446,6.627354,6.013501,6.662659,7.239450,0.0
14,77,63,3604782308,0,Subgroup C,0,1,29.455068,1,26398.00,...,19.675000,12.096739,15.002174,11.931214,12.367434,12.591340,12.110997,12.323376,12.820035,0.0
15,77,64,3604782308,0,Subgroup C,0,2,30.455068,1,26635.38,...,19.675000,12.096739,15.002174,11.931214,12.367434,12.591340,12.110997,12.323376,12.820035,0.0
16,18,65,3751034593,0,Subgroup C,0,1,8.192482,1,75948.12,...,22.222826,15.453261,19.189130,15.235160,15.641563,15.880552,15.352208,15.639668,16.352264,0.0
17,18,66,3751034593,0,Subgroup C,1,2,9.192482,1,77467.08,...,22.222826,15.453261,19.189130,15.235160,15.641563,15.880552,15.352208,15.639668,16.352264,-1.0
18,70,65,3995461216,1,Subgroup C,0,1,8.652450,1,64418.00,...,9.132609,9.509783,11.566304,6.310947,6.793513,7.018428,6.429297,7.091940,7.562930,0.0
19,70,66,3995461216,1,Subgroup C,0,2,9.652450,1,64418.00,...,9.132609,9.509783,11.566304,6.310947,6.793513,7.018428,6.429297,7.091940,7.562930,0.0
20,16,54,4272730483,0,Subgroup C,0,1,8.039159,1,64418.00,...,24.393478,20.632609,25.136957,16.267307,16.647480,17.134981,16.338554,17.019049,17.579762,0.0
21,16,55,4272730483,0,Subgroup C,0,2,9.039159,1,64418.00,...,24.393478,20.632609,25.136957,16.267307,16.647480,17.134981,16.338554,17.019049,17.579762,0.0
22,46,59,4496630010,0,Subgroup C,22,1,21.512399,1,64418.00,...,9.954348,11.550000,10.342391,4.940719,5.090395,5.077230,5.053551,5.154769,5.606865,0.0
23,46,60,4496630010,0,Subgroup C,57,2,22.512399,1,64418.00,...,9.954348,11.550000,10.342391,4.940719,5.090395,5.077230,5.053551,5.154769,5.606865,-35.0
24,9,46,4517852247,1,Subgroup C,0,1,10.084375,1,75000.00,...,7.938043,6.177174,7.708696,7.256826,7.304886,7.360177,7.244824,7.365504,7.560597,0.0
25,9,47,4517852247,1,Subgroup C,0,2,11.084375,1,77250.00,...,7.938043,6.177174,7.708696,7.256826,7.304886,7.360177,7.244824,7.365504,7.560597,0.0
26,69,40,4723372952,1,Subgroup C,0,1,15.053677,1,64418.00,...,9.072826,8.681522,9.335870,5.895154,6.130974,6.297318,5.976431,6.537423,7.158043,0.0
27,69,41,4723372952,1,Subgroup C,0,2,16.053677,1,64418.00,...,9.072826,8.681522,9.335870,5.895154,6.130974,6.297318,5.976431,6.537423,7.158043,0.0
28,50,42,5359159782,1,Subgroup C,0,1,25.753417,1,64418.00,...,10.290217,9.070652,11.053261,6.199946,6.496116,6.723905,5.991765,6.531004,7.068315,0.0
29,50,43,5359159782,1,Subgroup C,0,2,26.753417,1,64418.00,...,10.290217,9.070652,11.053261,6.199946,6.496116,6.723905,5.991765,6.531004,7.068315,0.0
30,17,59,5565515339,0,Subgroup C,215,1,11.009788,1,64418.00,...,17.438043,15.218478,16.961957,11.705788,11.869030,12.035485,11.762682,11.930742,12.292233,0.0
31,17,60,5565515339,0,Subgroup C,0,2,12.009788,1,64418.00,...,17.438043,15.218478,16.961957,11.705788,11.869030,12.035485,11.762682,11.930742,12.292233,215.0
32,77,61,5701617000,0,Subgroup C,0,1,38.128757,1,64418.00,...,19.675000,12.096739,15.002174,11.931214,12.367434,12.591340,12.110997,12.323376,12.820035,0.0
33,77,62,5701617000,0,Subgroup C,0,2,39.128757,1,64418.00,...,19.675000,12.096739,15.002174,11.931214,12.367434,12.591340,12.110997,12.323376,12.820035,0.0
34,45,40,5900341127,0,Subgroup C,0,1,26.572051,1,64418.00,...,6.879348,6.864130,8.877174,7.389416,7.911186,8.218315,7.393980,7.963938,8.513741,0.0
35,45,41,5900341127,0,Subgroup C,0,2,27.572051,1,64418.00,...,6.879348,6.864130,8.877174,7.389416,7.911186,8.218315,7.393980,7.963938,8.513741,0.0
37,75,53,6385399729,0,Subgroup C,24,1,16.633449,1,64418.00,...,11.127174,9.497826,13.091304,9.687205,10.035861,10.404627,9.684359,10.138121,11.045608,0.0
38,75,54,6385399729,0,Subgroup C,0,2,17.633449,1,64418.00,...,11.127174,9.497826,13.091304,9.687205,10.035861,10.404627,9.684359,10.138121,11.045608,24.0
40,61,49,6497530185,1,Subgroup C,0,1,14.133740,1,62256.14,...,13.151087,10.321739,11.076087,9.254983,9.716663,9.908102,9.034873,9.514288,10.380012,0.0
41,61,50,6497530185,1,Subgroup C,29,2,15.133740,1,62256.14,...,13.151087,10.321739,11.076087,9.254983,9.716663,9.908102,9.034873,9.514288,10.380012,-29.0
42,70,51,7167534435,0,Subgroup C,0,1,11.488922,1,64418.00,...,12.815217,14.553261,13.068478,6.269792,6.444521,6.531019,6.230951,6.360095,6.730507,0.0
43,57,52,7167534435,0,Subgroup C,0,2,12.488922,1,64418.00,...,12.726087,14.560870,13.382609,6.269792,6.444521,6.531019,6.230951,6.360095,6.730507,0.0
45,44,44,7523011392,0,Subgroup C,38,1,20.458305,1,61242.00,...,9.229348,9.375000,10.828261,5.908868,6.383102,6.633026,5.982096,6.625420,7.198879,0.0
46,44,45,7523011392,0,Subgroup C,191,2,21.458305,1,63079.26,...,9.229348,9.375000,10.828261,5.908868,6.383102,6.633026,5.982096,6.625420,7.198879,-153.0
47,37,53,8123004629,1,Subgroup C,0,1,17.181030,1,64356.46,...,9.217391,8.691304,10.089130,5.636002,5.962643,6.152243,5.756344,6.194422,6.422393,0.0
48,37,54,8123004629,1,Subgroup C,0,2,18.181030,1,66287.15,...,9.217391,8.691304,10.089130,5.636002,5.962643,6.152243,5.756344,6.194422,6.422393,0.0
49,76,51,9146624072,0,Subgroup C,0,1,16.545836,1,64418.00,...,8.661957,8.505435,11.120652,6.200609,6.682601,6.905563,6.320839,6.990297,7.477976,0.0
50,76,52,9146624072,0,Subgroup C,0,2,17.545836,1,64418.00,...,8.661957,8.505435,11.120652,6.200609,6.682601,6.905563,6.320839,6.990297,7.477976,0.0
52,70,43,9333359996,0,Subgroup C,0,1,14.133740,1,69951.11,...,13.698913,10.525000,11.689130,9.435450,9.882886,10.079435,9.226608,9.718864,10.570394,0.0
53,70,45,9333359996,0,Subgroup C,230,2,15.133740,1,71121.00,...,13.698913,10.525000,11.689130,9.435450,9.882886,10.079435,9.226608,9.718864,10.570394,-230.0
54,42,43,9441950135,0,Subgroup C,0,1,14.248732,1,64418.00,...,10.604348,10.141304,11.002174,6.033861,6.177977,6.312613,6.114251,6.530513,7.148746,0.0
55,42,45,9441950135,0,Subgroup C,0,2,15.248732,1,64418.00,...,10.604348,10.141304,11.002174,6.033861,6.177977,6.312613,6.114251,6.530513,7.148746,0.0
57,80,58,9483566774,1,Subgroup C,227,1,11.757237,1,64418.00,...,14.634783,7.872826,9.156522,7.727041,8.150968,8.377893,8.007907,8.408824,9.045990,0.0
58,80,58,9483566774,1,Subgroup C,246,2,12.757237,1,64418.00,...,14.634783,7.872826,9.156522,7.727041,8.150968,8.377893,8.007907,8.408824,9.045990,-19.0
59,50,33,9511794769,0,Subgroup C,55,1,10.377331,1,64418.00,...,10.043478,9.833696,10.661957,6.033861,6.177977,6.312613,6.114251,6.530513,7.148746,0.0
60,50,34,9511794769,0,Subgroup C,0,2,11.377331,1,64418.00,...,10.043478,9.833696,10.661957,6.033861,6.177977,6.312613,6.114251,6.530513,7.148746,55.0

In [278]:
year_1 = df_C_depression_1_2.loc[df_C_depression_1_2['analytic_period_id']==1][health_comparison_factors].reset_index(drop=True)
year_2 = df_C_depression_1_2.loc[df_C_depression_1_2['analytic_period_id']==2]['percentage_diff_absence'].reset_index(drop=True)

df_1_2 = year_1.merge(year_2, left_index=True, right_index=True,
                 how='outer', suffixes=('', '_y'))

df_1_2.drop(df_1_2.filter(regex='_y$').columns, axis=1, inplace=True)

df_1_2

,prog_1,prog_2,prog_3,prog_4,prog_5,prog_6,prog_7,prog_8,prog_9,prog_10,prog_11,prog_12,prog_13,prog_14,prog_15,prog_16,person_id,percentage_diff_absence
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1216979791,0.0
1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,1503980266,0.0
2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1712582566,0.0
3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2343841964,-79.0
4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,2432263119,0.0
5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,2824773588,0.0
6,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,3604782308,0.0
7,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,3751034593,-1.0
8,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,3995461216,0.0
9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,4272730483,0.0
10,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,4496630010,-35.0
11,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,4517852247,0.0
12,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,4723372952,0.0
13,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,5359159782,0.0
14,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,5565515339,215.0
15,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,5701617000,0.0
16,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,5900341127,0.0
17,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,6385399729,24.0
18,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,6497530185,-29.0
19,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,7167534435,0.0
20,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,7523011392,-153.0
21,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,8123004629,0.0
22,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,9146624072,0.0
23,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,9333359996,-230.0
24,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,9441950135,0.0
25,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,9483566774,-19.0
26,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,9511794769,55.0

In [279]:
counts = df_C_depression.groupby('person_id')['analytic_period_id'].unique()
person_ids_with_both_periods = [pid for pid, periods in counts.items() if 2 in periods and 3 in periods]

df_C_depression_2_3 = df_C_depression[df_C_depression['person_id'].isin(person_ids_with_both_periods)]
df_C_depression_2_3.reset_index(drop=True, inplace=True)
df_C_depression_2_3 = df_C_depression_2_3.loc[(df_C_depression_2_3['analytic_period_id']==2) | (df_C_depression_2_3['analytic_period_id']==3)]

df_C_depression_2_3

,ADI,Age,person_id,Gender,Subgroup,absence_indicator,analytic_period_id,tenure,overtime,salary,...,wildfire_potential_2018,wildfire_potential_2019,wildfire_potential_2019.1,wildfire_potential_ssp245_2025,wildfire_potential_ssp245_2035,wildfire_potential_ssp245_2045,wildfire_potential_ssp585_2025,wildfire_potential_ssp585_2035,wildfire_potential_ssp585_2045,percentage_diff_absence
0,80,49,1094883842,0,Subgroup C,0,2,31.251798,1,64418.00,...,18.093478,18.466304,16.157609,11.592954,11.850834,11.837443,11.439993,11.784370,12.120530,0.0
1,80,50,1094883842,0,Subgroup C,0,3,32.251798,1,64418.00,...,18.093478,18.466304,16.157609,11.592954,11.850834,11.837443,11.439993,11.784370,12.120530,0.0
2,86,62,1465426686,0,Subgroup C,0,2,11.224009,1,58811.45,...,8.984783,7.595652,9.960870,6.408431,6.931015,7.212014,6.527329,7.053106,7.476268,0.0
3,73,63,1465426686,0,Subgroup C,0,3,12.224009,1,60576.00,...,12.481522,10.159783,12.292391,7.367684,7.687450,7.769031,7.190298,7.583347,8.409759,0.0
5,4,56,1503980266,0,Subgroup C,0,2,13.140544,1,64418.00,...,3.848913,4.498913,5.517391,6.656552,6.736435,6.843538,6.623965,6.810580,6.960196,0.0
6,4,57,1503980266,0,Subgroup C,0,3,14.140544,1,64418.00,...,3.848913,4.498913,5.517391,6.656552,6.736435,6.843538,6.623965,6.810580,6.960196,0.0
7,38,36,2265588822,0,Subgroup C,0,2,11.683977,1,82627.30,...,11.051087,11.927174,12.232609,6.698873,6.901200,6.983719,6.720120,6.915153,7.282521,0.0
8,38,37,2265588822,0,Subgroup C,0,3,12.683977,1,85106.12,...,11.051087,11.927174,12.232609,6.698873,6.901200,6.983719,6.720120,6.915153,7.282521,0.0
10,64,46,2432263119,0,Subgroup C,0,2,7.141789,1,96900.00,...,31.029348,31.791304,34.463043,25.898552,26.188574,26.471987,25.735262,26.428740,27.669125,0.0
11,64,47,2432263119,0,Subgroup C,0,3,8.141789,1,100292.00,...,31.029348,31.791304,34.463043,25.898552,26.188574,26.471987,25.735262,26.428740,27.669125,0.0
12,42,60,3545522011,0,Subgroup C,0,2,12.527252,1,64418.00,...,9.798913,9.890217,11.740217,6.003101,6.479834,6.712516,6.082930,6.744432,7.322138,0.0
13,42,61,3545522011,0,Subgroup C,0,3,13.527252,1,64418.00,...,9.798913,9.890217,11.740217,6.003101,6.479834,6.712516,6.082930,6.744432,7.322138,0.0
14,45,56,4363234586,0,Subgroup C,0,2,17.874385,1,64418.00,...,13.061957,8.492391,10.448913,7.931101,8.381245,8.578490,8.111887,8.596949,9.243535,0.0
15,45,57,4363234586,0,Subgroup C,0,3,18.874385,1,64418.00,...,13.061957,8.492391,10.448913,7.931101,8.381245,8.578490,8.111887,8.596949,9.243535,0.0
16,64,39,4640665502,0,Subgroup C,0,2,9.249978,1,64418.00,...,9.894565,9.202174,10.396739,5.206681,5.385123,5.469699,5.307239,5.661267,6.101259,0.0
17,64,40,4640665502,0,Subgroup C,36,3,10.249978,1,64418.00,...,9.894565,9.202174,10.396739,5.206681,5.385123,5.469699,5.307239,5.661267,6.101259,-36.0
18,36,33,5252092168,0,Subgroup C,0,2,19.292621,1,64418.00,...,10.145652,10.481522,10.681522,6.601501,6.901109,7.083837,6.614857,7.057394,7.349958,0.0
19,36,34,5252092168,0,Subgroup C,0,3,20.292621,1,64418.00,...,10.145652,10.481522,10.681522,6.601501,6.901109,7.083837,6.614857,7.057394,7.349958,0.0
20,60,38,5484648669,0,Subgroup C,0,2,7.007632,1,64418.00,...,12.114130,11.998913,11.529348,6.466788,6.580212,6.533211,6.341136,6.471562,7.089128,0.0
21,60,39,5484648669,0,Subgroup C,0,3,8.007632,1,64418.00,...,12.114130,11.998913,11.529348,6.466788,6.580212,6.533211,6.341136,6.471562,7.089128,0.0
23,45,41,5900341127,0,Subgroup C,0,2,27.572051,1,64418.00,...,6.879348,6.864130,8.877174,7.389416,7.911186,8.218315,7.393980,7.963938,8.513741,0.0
24,45,42,5900341127,0,Subgroup C,125,3,28.572051,1,64418.00,...,6.879348,6.864130,8.877174,7.389416,7.911186,8.218315,7.393980,7.963938,8.513741,-125.0
26,75,54,6385399729,0,Subgroup C,0,2,17.633449,1,64418.00,...,11.127174,9.497826,13.091304,9.687205,10.035861,10.404627,9.684359,10.138121,11.045608,24.0
27,75,55,6385399729,0,Subgroup C,0,3,18.633449,1,64418.00,...,11.127174,9.497826,13.091304,9.687205,10.035861,10.404627,9.684359,10.138121,11.045608,0.0
29,57,52,7167534435,0,Subgroup C,0,2,12.488922,1,64418.00,...,12.726087,14.560870,13.382609,6.269792,6.444521,6.531019,6.230951,6.360095,6.730507,0.0
30,57,53,7167534435,0,Subgroup C,0,3,13.488922,1,64418.00,...,12.726087,14.560870,13.382609,6.269792,6.444521,6.531019,6.230951,6.360095,6.730507,0.0
31,72,48,7315414076,0,Subgroup C,0,2,14.827094,1,64418.00,...,9.435870,9.252174,11.648913,6.131013,6.593098,6.822279,6.263953,6.924475,7.399274,0.0
32,72,49,7315414076,0,Subgroup C,0,3,15.827094,1,64418.00,...,9.435870,9.252174,11.648913,6.131013,6.593098,6.822279,6.263953,6.924475,7.399274,0.0
33,10,50,7335873299,1,Subgroup C,178,2,13.638843,1,71270.00,...,22.144565,19.177174,20.967391,11.005414,11.161228,11.311914,11.043097,11.253615,11.613303,0.0
34,10,51,7335873299,1,Subgroup C,0,3,14.638843,1,69194.00,...,22.144565,19.177174,20.967391,11.005414,11.161228,11.311914,11.043097,11.253615,11.613303,178.0
35,57,50,7555596280,1,Subgroup C,0,2,17.337755,1,84835.25,...,11.397826,11.411957,10.583696,4.889798,5.110482,5.087351,4.961411,5.137876,5.678932,0.0
36,57,51,7555596280,1,Subgroup C,0,3,18.337755,1,87211.00,...,11.397826,11.411957,10.583696,4.889798,5.110482,5.087351,4.961411,5.137876,5.678932,0.0
37,45,43,7642615373,0,Subgroup C,0,2,23.049029,1,43068.00,...,6.652174,6.355435,8.457609,7.290190,7.820141,8.152020,7.299540,7.878583,8.454539,0.0
38,45,44,7642615373,0,Subgroup C,0,3,24.049029,1,44025.02,...,6.652174,6.355435,8.457609,7.290190,7.820141,8.152020,7.299540,7.878583,8.454539,0.0
39,51,31,8544925855,1,Subgroup C,0,2,11.804445,1,118279.41,...,16.238043,8.843478,10.896739,10.040186,10.365548,10.588679,10.187517,10.628950,11.381718,0.0
40,51,32,8544925855,1,Subgroup C,0,3,12.804445,1,121828.00,...,16.238043,8.843478,10.896739,10.040186,10.365548,10.588679,10.187517,10.628950,11.381718,0.0
41,27,37,9114212147,0,Subgroup C,0,2,11.109017,1,53235.00,...,9.403261,9.655435,11.720652,6.003201,6.482577,6.724924,6.080874,6.738228,7.317786,0.0
42,27,38,9114212147,0,Subgroup C,0,3,12.109017,1,54779.00,...,9.403261,9.655435,11.720652,6.003201,6.482577,6.724924,6.080874,6.738228,7.317786,0.0
44,76,52,9146624072,0,Subgroup C,0,2,17.545836,1,64418.00,...,8.661957,8.505435,11.120652,6.200609,6.682601,6.905563,6.320839,6.990297,7.477976,0.0
45,76,53,9146624072,0,Subgroup C,0,3,18.545836,1,64418.00,...,8.661957,8.505435,11.120652,6.200609,6.682601,6.905563,6.320839,6.990297,7.477976,0.0
46,52,29,9207492617,0,Subgroup C,0,2,9.384135,1,47722.00,...,8.769565,9.041304,10.921739,5.928487,6.382446,6.627354,6.013501,6.662659,7.239450,0.0
47,52,30,9207492617,0,Subgroup C,0,3,10.384135,1,61460.28,...,8.769565,9.041304,10.921739,5.928487,6.382446,6.627354,6.013501,6.662659,7.239450,0.0
49,42,45,9441950135,0,Subgroup C,0,2,15.248732,1,64418.00,...,10.604348,10.141304,11.002174,6.033861,6.177977,6.312613,6.114251,6.530513,7.148746,0.0
50,40,46,9441950135,0,Subgroup C,0,3,16.248732,1,64418.00,...,10.386957,10.110870,10.928261,6.033861,6.177977,6.312613,6.114251,6.530513,7.148746,0.0
52,50,34,9511794769,0,Subgroup C,0,2,11.377331,1,64418.00,...,10.043478,9.833696,10.661957,6.033861,6.177977,6.312613,6.114251,6.530513,7.148746,55.0
53,50,35,9511794769,0,Subgroup C,0,3,12.377331,1,64418.00,...,10.043478,9.833696,10.661957,6.033861,6.177977,6.312613,6.114251,6.530513,7.148746,0.0

In [280]:
year_2 = df_C_depression_2_3.loc[df_C_depression_2_3['analytic_period_id']==2][health_comparison_factors].reset_index(drop=True)
year_3 = df_C_depression_2_3.loc[df_C_depression_2_3['analytic_period_id']==3]['percentage_diff_absence'].reset_index(drop=True)

df_2_3 = year_2.merge(year_3, left_index=True, right_index=True,
                 how='outer', suffixes=('', '_y'))

df_2_3.drop(df_2_3.filter(regex='_y$').columns, axis=1, inplace=True)

df_2_3

,prog_1,prog_2,prog_3,prog_4,prog_5,prog_6,prog_7,prog_8,prog_9,prog_10,prog_11,prog_12,prog_13,prog_14,prog_15,prog_16,person_id,percentage_diff_absence
0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,1094883842,0.0
1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,1465426686,0.0
2,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,1503980266,0.0
3,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,2265588822,0.0
4,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,2432263119,0.0
5,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,3545522011,0.0
6,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,4363234586,0.0
7,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,4640665502,-36.0
8,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,5252092168,0.0
9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,5484648669,0.0
10,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1,5900341127,-125.0
11,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,6385399729,0.0
12,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,7167534435,0.0
13,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,7315414076,0.0
14,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,7335873299,178.0
15,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,7555596280,0.0
16,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,7642615373,0.0
17,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,8544925855,0.0
18,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1,9114212147,0.0
19,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,9146624072,0.0
20,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,9207492617,0.0
21,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1,9441950135,0.0
22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,9511794769,0.0

In [281]:
# train data: 2019 - 2018
# test data: 2020 - 2019

# get data from person_id with both analytic_period_id 1 and 2

from sklearn.model_selection import train_test_split

y_train = pd.DataFrame(df_1_2['percentage_diff_absence'])
y_train.loc[y_train['percentage_diff_absence'] > 0, 'percentage_diff_absence'] = np.log(y_train.loc[y_train['percentage_diff_absence'] > 0, 'percentage_diff_absence'])
y_train.loc[y_train['percentage_diff_absence'] < 0, 'percentage_diff_absence'] = -np.log(-y_train.loc[y_train['percentage_diff_absence'] < 0, 'percentage_diff_absence'])
x_train = pd.DataFrame(df_1_2[health_programs])
x_train[health_programs] = x_train[health_programs].astype('category')

y_test = pd.DataFrame(df_2_3['percentage_diff_absence'])
y_test.loc[y_test['percentage_diff_absence'] > 0, 'percentage_diff_absence'] = np.log(y_test.loc[y_test['percentage_diff_absence'] > 0, 'percentage_diff_absence'])
y_test.loc[y_test['percentage_diff_absence'] < 0, 'percentage_diff_absence'] = -np.log(-y_test.loc[y_test['percentage_diff_absence'] < 0, 'percentage_diff_absence'])
x_test = pd.DataFrame(df_2_3[health_programs])
x_test[health_programs] = x_test[health_programs].astype('category')

print("Train Set :", y_train.shape, x_train.shape)
print("Test Set  :", y_test.shape, x_test.shape)

Train Set : (27, 1) (27, 16)
Test Set  : (23, 1) (23, 16)

In [282]:
# use Linear Regression

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

linreg = LinearRegression()

linreg.fit(x_train, y_train)

print('Intercept of Regression \t: b = ', linreg.intercept_)

y_train_pred = linreg.predict(x_train)
y_test_pred = linreg.predict(x_test)

# Check the Goodness of Fit (on Train Data)
print("Goodness of Fit of Model \tTrain Dataset")
print("Explained Variance (R^2) \t:", linreg.score(x_train, y_train))
print("Mean Squared Error (MSE) \t:", mean_squared_error(y_train, y_train_pred))
print()

# Check the Goodness of Fit (on Test Data)
print("Goodness of Fit of Model \tTest Dataset")
print("Explained Variance (R^2) \t:", linreg.score(x_test, y_test))
print("Mean Squared Error (MSE) \t:", mean_squared_error(y_test, y_test_pred))
print()

Intercept of Regression 	: b =  [-2.6349646]
Goodness of Fit of Model 	Train Dataset
Explained Variance (R^2) 	: 0.38598766397922446
Mean Squared Error (MSE) 	: 3.551148675810843

Goodness of Fit of Model 	Test Dataset
Explained Variance (R^2) 	: -0.0323408694090368
Mean Squared Error (MSE) 	: 2.807584935845621

In [283]:
import statsmodels.api as sm

x_train_with_constant = sm.add_constant(x_train)
model = sm.OLS(y_train, x_train_with_constant)
result = model.fit()

print(result.summary())

                               OLS Regression Results
===================================================================================
Dep. Variable:     percentage_diff_absence   R-squared:                       0.386
Model:                                 OLS   Adj. R-squared:                  0.274
Method:                      Least Squares   F-statistic:                     3.457
Date:                     Sat, 06 Apr 2024   Prob (F-statistic):             0.0245
Time:                             20:55:18   Log-Likelihood:                -55.420
No. Observations:                       27   AIC:                             120.8
Df Residuals:                           22   BIC:                             127.3
Df Model:                                4
Covariance Type:                 nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         -2.6350      0.934     -2.822      0.010      -4.571      -0.699
prog_1      6.406e-16    2.5e-16      2.567      0.018    1.23e-16    1.16e-15
prog_2        -2.4179      1.328     -1.820      0.082      -5.172       0.337
prog_3      1.966e-16   2.03e-16      0.966      0.344   -2.25e-16    6.19e-16
prog_4      9.392e-16   4.95e-16      1.899      0.071   -8.64e-17    1.96e-15
prog_5              0          0        nan        nan           0           0
prog_6              0          0        nan        nan           0           0
prog_7              0          0        nan        nan           0           0
prog_8        -0.2513      1.184     -0.212      0.834      -2.706       2.203
prog_9              0          0        nan        nan           0           0
prog_10             0          0        nan        nan           0           0
prog_11             0          0        nan        nan           0           0
prog_12             0          0        nan        nan           0           0
prog_13             0          0        nan        nan           0           0
prog_14             0          0        nan        nan           0           0
prog_15        3.7560      2.161      1.738      0.096      -0.725       8.237
prog_16        2.8863      1.088      2.654      0.015       0.631       5.142
==============================================================================
Omnibus:                        5.202   Durbin-Watson:                   2.488
Prob(Omnibus):                  0.074   Jarque-Bera (JB):                5.006
Skew:                           0.153   Prob(JB):                       0.0818
Kurtosis:                       5.087   Cond. No.                     1.78e+84
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 1.5e-167. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

In [284]:
# use decision tree regressor

from sklearn.tree import DecisionTreeRegressor

decisiontreemodel = DecisionTreeRegressor(max_depth=3)
result = decisiontreemodel.fit(x_train, y_train)

y_train_pred = decisiontreemodel.predict(x_train)
train_mse = mean_squared_error(y_train_pred, y_train)
y_test_pred = decisiontreemodel.predict(x_test)
test_mse = mean_squared_error(y_test_pred, y_test)

print("Mean Squared Error (Train Dataset):", train_mse)
print("Mean Squared Error (Test Dataset):", test_mse)

Mean Squared Error (Train Dataset): 3.5584256368724545
Mean Squared Error (Test Dataset): 2.6504665294174474

In [285]:
from sklearn.model_selection import GridSearchCV

param_grid = {'max_depth': range(1, 11)}

decisiontreemodel = DecisionTreeRegressor()

grid_search = GridSearchCV(estimator=decisiontreemodel, param_grid=param_grid, cv=5)

grid_search.fit(x_train, y_train)
best_max_depth = grid_search.best_params_['max_depth']

print("Best max_depth:", best_max_depth)

Best max_depth: 3

In [286]:
# use decision tree regressor

from sklearn.tree import DecisionTreeRegressor

decisiontreemodel = DecisionTreeRegressor(max_depth=best_max_depth)
result = decisiontreemodel.fit(x_train, y_train)

y_train_pred = decisiontreemodel.predict(x_train)
train_mse = mean_squared_error(y_train_pred, y_train)
y_test_pred = decisiontreemodel.predict(x_test)
test_mse = mean_squared_error(y_test_pred, y_test)

print("Mean Squared Error (Train Dataset):", train_mse)
print("Mean Squared Error (Test Dataset):", test_mse)

Mean Squared Error (Train Dataset): 3.5584256368724545
Mean Squared Error (Test Dataset): 2.6504665294174474

In [287]:
significant_variable = {}
significant_variable['significant_variables'] = []
fr = decisiontreemodel.feature_importances_ 
importance_dict = dict(zip(x_train.columns, fr))
for key in importance_dict:
    if importance_dict[key] > 0:
        significant_variable['significant_variables'].append(key)
        
print(significant_variable)

{'significant_variables': ['prog_2', 'prog_15', 'prog_16']}

In [288]:
from sklearn.ensemble import RandomForestRegressor

randomforest = RandomForestRegressor(n_estimators=100, max_depth=5, random_state=42)
randomforest.fit(x_train, y_train)

y_train_pred = randomforest.predict(x_train)
train_mse = mean_squared_error(y_train_pred, y_train)
y_test_pred = randomforest.predict(x_test)
test_mse = mean_squared_error(y_test_pred, y_test)

print("Mean Squared Error (Train Dataset):", train_mse)
print("Mean Squared Error (Test Dataset):", test_mse)

Mean Squared Error (Train Dataset): 3.6206452253032557
Mean Squared Error (Test Dataset): 2.7139835652893063

C:\Users\Willis\AppData\Local\Temp\ipykernel_26140\458196643.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  randomforest.fit(x_train, y_train)

In [289]:
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint

param_dist = {
    'n_estimators': randint(50, 200),
    'max_depth': [None] + list(range(5, 20)),
    'min_samples_split': randint(2, 20)
}

randomized_search = RandomizedSearchCV(estimator=RandomForestRegressor(), param_distributions=param_dist, n_iter=5, cv=5, scoring='neg_mean_squared_error', random_state=42)

randomized_search.fit(x_train, y_train)

best_params = randomized_search.best_params_
print(best_params)

C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)

{'max_depth': 8, 'min_samples_split': 5, 'n_estimators': 153}

C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Willis\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:909: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self.best_estimator_.fit(X, y, **fit_params)

In [290]:
randomforest = RandomForestRegressor(n_estimators=best_params['n_estimators'], max_depth=best_params['max_depth'], min_samples_split=best_params['min_samples_split'], random_state=42)
randomforest.fit(x_train, y_train)

y_train_pred = randomforest.predict(x_train)
train_mse = mean_squared_error(y_train_pred, y_train)
y_test_pred = randomforest.predict(x_test)
test_mse = mean_squared_error(y_test_pred, y_test)

print("Mean Squared Error (Train Dataset):", train_mse)
print("Mean Squared Error (Test Dataset):", test_mse)

Mean Squared Error (Train Dataset): 3.6143577045042217
Mean Squared Error (Test Dataset): 2.708184321895152

C:\Users\Willis\AppData\Local\Temp\ipykernel_26140\3010193299.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  randomforest.fit(x_train, y_train)

In [291]:
feature_importances = randomforest.feature_importances_
feature_importance_dict = dict(zip(x_train.columns, feature_importances))
sorted_features = sorted(feature_importance_dict.items(), key=lambda x: x[1], reverse=True)

sorted_features

[('prog_16', 0.4577666739292999),
 ('prog_15', 0.2629951767575503),
 ('prog_2', 0.2567012783492155),
 ('prog_8', 0.022536870963934263),
 ('prog_1', 0.0),
 ('prog_3', 0.0),
 ('prog_4', 0.0),
 ('prog_5', 0.0),
 ('prog_6', 0.0),
 ('prog_7', 0.0),
 ('prog_9', 0.0),
 ('prog_10', 0.0),
 ('prog_11', 0.0),
 ('prog_12', 0.0),
 ('prog_13', 0.0),
 ('prog_14', 0.0)]