In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb

sb.set()

In [2]:
df = pd.read_csv('Dataset.csv', index_col=0)
df.head()

,ADI,Age,person_id,Gender,Subgroup,absence_indicator,analytic_period_id,tenure,overtime,salary,...,extreme_heat_ssp585_2045,wildfire_potential_2018,wildfire_potential_2019,wildfire_potential_2019.1,wildfire_potential_ssp245_2025,wildfire_potential_ssp245_2035,wildfire_potential_ssp245_2045,wildfire_potential_ssp585_2025,wildfire_potential_ssp585_2035,wildfire_potential_ssp585_2045
0,28,37,3030515063,Male,Subgroup P,0,1,18.25,1,115700.0,...,13.380953,10.975000,11.460870,12.070652,6.033403,6.347014,6.512159,6.093082,6.504460,6.743331
1,18,34,9786383567,Male,Subgroup P,0,1,3.99,7,81435.0,...,13.380953,11.141304,11.520652,11.871739,6.033403,6.347014,6.512159,6.093082,6.504460,6.743331
2,15,36,5602306401,Male,Subgroup P,0,1,3.05,1,86400.0,...,15.597403,10.393478,10.777174,11.659783,6.064177,6.380910,6.548825,6.117186,6.522880,6.771772
3,36,41,8107765424,Male,Subgroup P,0,1,20.29,1,79176.0,...,12.290043,11.039130,11.023913,11.963043,6.069724,6.365864,6.512409,6.091926,6.469195,6.700504
4,49,51,7879842771,Male,Subgroup P,0,1,13.66,7,94511.0,...,12.290043,10.760870,11.308696,12.006522,6.069724,6.365864,6.512409,6.091926,6.469195,6.700504

In [3]:
# set gender to 1 and 0

df['Gender'] = np.where(df['Gender'] == 'Male', 1, 0)
df.head()

,ADI,Age,person_id,Gender,Subgroup,absence_indicator,analytic_period_id,tenure,overtime,salary,...,extreme_heat_ssp585_2045,wildfire_potential_2018,wildfire_potential_2019,wildfire_potential_2019.1,wildfire_potential_ssp245_2025,wildfire_potential_ssp245_2035,wildfire_potential_ssp245_2045,wildfire_potential_ssp585_2025,wildfire_potential_ssp585_2035,wildfire_potential_ssp585_2045
0,28,37,3030515063,1,Subgroup P,0,1,18.25,1,115700.0,...,13.380953,10.975000,11.460870,12.070652,6.033403,6.347014,6.512159,6.093082,6.504460,6.743331
1,18,34,9786383567,1,Subgroup P,0,1,3.99,7,81435.0,...,13.380953,11.141304,11.520652,11.871739,6.033403,6.347014,6.512159,6.093082,6.504460,6.743331
2,15,36,5602306401,1,Subgroup P,0,1,3.05,1,86400.0,...,15.597403,10.393478,10.777174,11.659783,6.064177,6.380910,6.548825,6.117186,6.522880,6.771772
3,36,41,8107765424,1,Subgroup P,0,1,20.29,1,79176.0,...,12.290043,11.039130,11.023913,11.963043,6.069724,6.365864,6.512409,6.091926,6.469195,6.700504
4,49,51,7879842771,1,Subgroup P,0,1,13.66,7,94511.0,...,12.290043,10.760870,11.308696,12.006522,6.069724,6.365864,6.512409,6.091926,6.469195,6.700504

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 43184 entries, 0 to 43183
Data columns (total 74 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   ADI                                 43184 non-null  int64
 1   Age                                 43184 non-null  int64
 2   person_id                           43184 non-null  int64
 3   Gender                              43184 non-null  int64
 4   Subgroup                            43184 non-null  object
 5   absence_indicator                   43184 non-null  int64
 6   analytic_period_id                  43184 non-null  int64
 7   tenure                              43184 non-null  float64
 8   overtime                            43184 non-null  int64
 9   salary                              43184 non-null  float64
 10  performance_rating                  43184 non-null  int64
 11  BiometricScreeningParticipants      43184 non-null  int64
 12  HRQParticipants                     43184 non-null  int64
 13  lsbio_cholesterol                   43184 non-null  int64
 14  lsbio_glucose                       43184 non-null  int64
 15  lsbio_bp                            43184 non-null  int64
 16  lsbio_weight                        43184 non-null  int64
 17  lsbio_trig                          43184 non-null  int64
 18  lshrq_physact                       43184 non-null  int64
 19  lshrq_tobacco                       43184 non-null  int64
 20  lshrq_nutrition                     43184 non-null  int64
 21  lshrq_stress                        43184 non-null  int64
 22  lshrq_genHealth                     43184 non-null  int64
 23  lshrq_wellbeing                     43184 non-null  int64
 24  lshrq_alcohol                       43184 non-null  int64
 25  lshrq_sleeping                      43184 non-null  int64
 26  cc_RespiratorySinusAllergy_chronic  43184 non-null  int64
 27  cc_diabetes                         43184 non-null  int64
 28  cc_cancer                           43184 non-null  int64
 29  cc_mskChronic                       43184 non-null  int64
 30  cc_cholesterol                      43184 non-null  int64
 31  cc_cardiac                          43184 non-null  int64
 32  cc_depression                       43184 non-null  int64
 33  cc_obesity                          43184 non-null  int64
 34  cc_mskAllOther                      43184 non-null  int64
 35  cc_behavioralAllOther               43184 non-null  int64
 36  cc_ckd                              43184 non-null  int64
 37  concurrent_risk                     43184 non-null  float64
 38  rx_nonClaimant                      43184 non-null  int64
 39  rx_nonCompliant                     43184 non-null  int64
 40  prog_1                              43184 non-null  int64
 41  prog_2                              43184 non-null  int64
 42  prog_3                              43184 non-null  int64
 43  prog_4                              43184 non-null  int64
 44  prog_5                              43184 non-null  int64
 45  prog_6                              43184 non-null  int64
 46  prog_7                              43184 non-null  int64
 47  prog_8                              43184 non-null  int64
 48  prog_9                              43184 non-null  int64
 49  prog_10                             43184 non-null  int64
 50  prog_11                             43184 non-null  int64
 51  prog_12                             43184 non-null  int64
 52  prog_13                             43184 non-null  int64
 53  prog_14                             43184 non-null  int64
 54  prog_15                             43184 non-null  int64
 55  prog_16                             43184 non-null  int64
 56  extreme_heat_2018                   43184 non-null  int64
 57  extreme_heat_2019                   43184 non-null  int64
 58  extreme_heat_2020                   43184 non-null  int64
 59  extreme_heat_ssp245_2025            43184 non-null  float64
 60  extreme_heat_ssp245_2035            43184 non-null  float64
 61  extreme_heat_ssp245_2045            43184 non-null  float64
 62  extreme_heat_ssp585_2025            43184 non-null  float64
 63  extreme_heat_ssp585_2035            43184 non-null  float64
 64  extreme_heat_ssp585_2045            43184 non-null  float64
 65  wildfire_potential_2018             43184 non-null  float64
 66  wildfire_potential_2019             43184 non-null  float64
 67  wildfire_potential_2019.1           43184 non-null  float64
 68  wildfire_potential_ssp245_2025      43184 non-null  float64
 69  wildfire_potential_ssp245_2035      43184 non-null  float64
 70  wildfire_potential_ssp245_2045      43184 non-null  float64
 71  wildfire_potential_ssp585_2025      43184 non-null  float64
 72  wildfire_potential_ssp585_2035      43184 non-null  float64
 73  wildfire_potential_ssp585_2045      43184 non-null  float64
dtypes: float64(18), int64(55), object(1)
memory usage: 24.7+ MB

In [12]:
df_P = df.loc[df['Subgroup']=='Subgroup P'].reset_index(drop=True)

df_P

,ADI,Age,person_id,Gender,Subgroup,absence_indicator,analytic_period_id,tenure,overtime,salary,...,extreme_heat_ssp585_2045,wildfire_potential_2018,wildfire_potential_2019,wildfire_potential_2019.1,wildfire_potential_ssp245_2025,wildfire_potential_ssp245_2035,wildfire_potential_ssp245_2045,wildfire_potential_ssp585_2025,wildfire_potential_ssp585_2035,wildfire_potential_ssp585_2045
0,28,37,3030515063,1,Subgroup P,0,1,18.25,1,115700.0,...,13.380953,10.975000,11.460870,12.070652,6.033403,6.347014,6.512159,6.093082,6.504460,6.743331
1,18,34,9786383567,1,Subgroup P,0,1,3.99,7,81435.0,...,13.380953,11.141304,11.520652,11.871739,6.033403,6.347014,6.512159,6.093082,6.504460,6.743331
2,15,36,5602306401,1,Subgroup P,0,1,3.05,1,86400.0,...,15.597403,10.393478,10.777174,11.659783,6.064177,6.380910,6.548825,6.117186,6.522880,6.771772
3,36,41,8107765424,1,Subgroup P,0,1,20.29,1,79176.0,...,12.290043,11.039130,11.023913,11.963043,6.069724,6.365864,6.512409,6.091926,6.469195,6.700504
4,49,51,7879842771,1,Subgroup P,0,1,13.66,7,94511.0,...,12.290043,10.760870,11.308696,12.006522,6.069724,6.365864,6.512409,6.091926,6.469195,6.700504
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19618,29,29,2451211379,0,Subgroup P,0,3,3.15,1,82400.0,...,15.597403,10.598913,10.661957,11.409783,6.064177,6.380910,6.548825,6.117186,6.522880,6.771772
19619,28,33,2628362842,1,Subgroup P,0,3,2.98,1,82400.0,...,15.597403,10.372826,10.489130,11.231522,6.064177,6.380910,6.548825,6.117186,6.522880,6.771772
19620,20,43,6699447122,1,Subgroup P,0,3,6.63,1,103000.0,...,13.380953,11.095652,11.556522,12.109783,6.033403,6.347014,6.512159,6.093082,6.504460,6.743331
19621,20,28,1981658758,1,Subgroup P,0,3,4.25,1,79000.0,...,18.709957,9.895652,9.854348,10.597826,6.123318,6.446156,6.621974,6.162228,6.574199,6.841721
19622,14,41,2713117471,1,Subgroup P,1,3,2.96,1,91100.0,...,13.731602,9.442391,9.752174,10.917391,5.881690,6.203235,6.383163,5.963483,6.392136,6.643947

In [13]:
df_C = df.loc[df['Subgroup']=='Subgroup C'].reset_index(drop=True)

df_C

,ADI,Age,person_id,Gender,Subgroup,absence_indicator,analytic_period_id,tenure,overtime,salary,...,extreme_heat_ssp585_2045,wildfire_potential_2018,wildfire_potential_2019,wildfire_potential_2019.1,wildfire_potential_ssp245_2025,wildfire_potential_ssp245_2035,wildfire_potential_ssp245_2045,wildfire_potential_ssp585_2025,wildfire_potential_ssp585_2035,wildfire_potential_ssp585_2045
0,11,37,8546337240,1,Subgroup C,88,1,17.621833,1,87639.00,...,22.606060,20.069565,19.326087,22.286957,12.084754,12.515748,12.869328,12.338427,12.880823,13.652612
1,59,30,4414458229,0,Subgroup C,0,1,10.990623,1,64418.00,...,30.393940,8.805435,8.142391,8.914130,5.748487,5.972501,6.138339,5.835410,6.371663,6.963992
2,61,28,9953807739,1,Subgroup C,0,1,9.534056,1,32779.00,...,63.987010,13.167391,10.141304,11.293478,9.254983,9.716663,9.908102,9.034873,9.514288,10.380012
3,69,45,3512709535,0,Subgroup C,0,1,9.419064,1,64418.00,...,30.952381,9.072826,8.681522,9.335870,5.895154,6.130974,6.297318,5.976431,6.537423,7.158043
4,34,52,3553003505,1,Subgroup C,0,1,10.254126,1,24414.33,...,14.709957,9.011957,8.191304,9.889130,6.199946,6.496116,6.723905,5.991765,6.531004,7.068315
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23556,28,38,4607985867,1,Subgroup C,0,3,14.907158,1,53998.00,...,17.696970,8.976087,9.318478,10.951087,6.191511,6.697415,6.946731,6.263153,6.928876,7.508470
23557,66,38,8195942622,1,Subgroup C,0,3,24.462453,1,64418.00,...,12.428572,8.947826,8.775000,11.314130,7.716896,8.310183,8.602780,7.826232,8.456431,8.992498
23558,53,40,4998061809,0,Subgroup C,0,3,15.788764,1,64418.00,...,75.147190,14.614130,12.535870,13.615217,11.246546,11.606987,11.760611,11.311094,11.540871,11.855016
23559,37,53,7004427645,0,Subgroup C,0,3,9.080891,1,151792.46,...,39.822510,11.560870,12.789130,11.771739,5.915788,6.011025,5.979647,5.895722,6.030750,6.580437
23560,38,27,4330728686,0,Subgroup C,0,3,9.349206,1,64418.00,...,17.969696,9.425000,9.743478,11.846739,6.003201,6.482577,6.724924,6.080874,6.738228,7.317786

In [14]:
health_programs = ['prog_1', 'prog_2', 'prog_3', 'prog_4', 'prog_5', 'prog_6', 'prog_7', 'prog_8', 'prog_9', 
                   'prog_10', 'prog_11', 'prog_12', 'prog_13', 'prog_14', 'prog_15', 'prog_16']

### Subgroup P

#### cc_mskChronic

In [87]:
df_P_mskChronic = df_P.loc[(df_P['cc_mskChronic'] == 1) & 
                           (df_P['cc_diabetes'] != 1) & 
                           (df_P['cc_cardiac'] != 1)].reset_index(drop=True)

df_P_mskChronic = df_P_mskChronic.sort_values(by=['person_id', 'analytic_period_id'])

df_P_mskChronic['percentage_diff_absence'] = round((df_P_mskChronic.groupby('person_id')['absence_indicator'].diff() * -1),0)

df_P_mskChronic['percentage_diff_absence'] = df_P_mskChronic['percentage_diff_absence'].fillna(0)

df_P_mskChronic['percentage_diff_absence'] = np.where(df_P_mskChronic['percentage_diff_absence']== -0, 0, df_P_mskChronic['percentage_diff_absence'])

df_P_mskChronic[health_programs] = np.where(df_P_mskChronic[health_programs] == -1, 0, df_P_mskChronic[health_programs])

df_P_mskChronic

,ADI,Age,person_id,Gender,Subgroup,absence_indicator,analytic_period_id,tenure,overtime,salary,...,wildfire_potential_2018,wildfire_potential_2019,wildfire_potential_2019.1,wildfire_potential_ssp245_2025,wildfire_potential_ssp245_2035,wildfire_potential_ssp245_2045,wildfire_potential_ssp585_2025,wildfire_potential_ssp585_2035,wildfire_potential_ssp585_2045,percentage_diff_absence
1441,28,39,1006971219,1,Subgroup P,0,2,7.15,1,131000.0,...,9.792391,9.869565,10.609783,6.076034,6.377780,6.529870,6.091510,6.460996,6.703535,0.0
1872,21,53,1010658764,1,Subgroup P,0,2,34.36,5,133600.0,...,10.078261,10.346739,10.439130,6.507597,6.792691,6.960008,6.481590,6.892562,7.170657,0.0
2801,25,45,1013214811,1,Subgroup P,0,3,7.46,5,104300.0,...,9.088043,9.164130,10.404348,5.803466,6.141432,6.357934,5.922491,6.452889,6.790101,0.0
698,29,31,1016218037,1,Subgroup P,0,1,10.18,7,89780.0,...,10.598913,10.661957,11.409783,6.064177,6.380910,6.548825,6.117186,6.522880,6.771772,0.0
2002,29,32,1016218037,1,Subgroup P,0,2,11.18,5,92475.0,...,10.598913,10.661957,11.409783,6.064177,6.380910,6.548825,6.117186,6.522880,6.771772,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
987,21,60,9995325405,1,Subgroup P,0,1,39.03,7,97914.0,...,10.758696,10.884783,11.782609,6.033403,6.347014,6.512159,6.093082,6.504460,6.743331,0.0
2299,39,43,9995527821,1,Subgroup P,0,2,5.80,1,97700.0,...,9.285870,9.185870,10.282609,5.511195,5.851079,6.076424,5.649698,6.112522,6.391492,0.0
2471,18,38,9995667595,1,Subgroup P,0,2,11.51,1,94014.0,...,8.704348,9.220652,10.250000,5.464575,5.759225,5.909338,5.546726,5.922153,6.124357,0.0
766,39,30,9999617900,1,Subgroup P,9,1,10.33,7,101031.0,...,9.723913,9.852174,9.997826,6.341523,6.605085,6.750162,6.280464,6.651682,6.912897,0.0
2055,39,31,9999617900,1,Subgroup P,2,2,11.34,5,104062.0,...,9.723913,9.852174,9.997826,6.341523,6.605085,6.750162,6.280464,6.651682,6.912897,7.0

In [88]:
# try and clean the data chronic =1 all must be equal 1

In [89]:
# train data: 2019 - 2018
# test data: 2020 - 2019

y = pd.DataFrame(df_P_mskChronic.loc[df_P_mskChronic['analytic_period_id']==2]['percentage_diff_absence'])

x = df_P_mskChronic.loc[df_P_mskChronic['analytic_period_id']==1][health_programs]

x

,prog_1,prog_2,prog_3,prog_4,prog_5,prog_6,prog_7,prog_8,prog_9,prog_10,prog_11,prog_12,prog_13,prog_14,prog_15,prog_16
698,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0
45,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
792,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
545,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0
147,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
528,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0
478,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0
1395,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0
987,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
766,0,0,0,1,0,0,0,0,0,0,1,1,0,1,0,0