In [2]:
import pandas as pd
import numpy as np

In [11]:
df = pd.read_csv('Dataset.csv', index_col=0)
df.head()

,ADI,Age,person_id,Gender,Subgroup,absence_indicator,analytic_period_id,tenure,overtime,salary,...,extreme_heat_ssp585_2045,wildfire_potential_2018,wildfire_potential_2019,wildfire_potential_2019.1,wildfire_potential_ssp245_2025,wildfire_potential_ssp245_2035,wildfire_potential_ssp245_2045,wildfire_potential_ssp585_2025,wildfire_potential_ssp585_2035,wildfire_potential_ssp585_2045
0,28,37,3030515063,Male,Subgroup P,0,1,18.25,1,115700.0,...,13.380953,10.975000,11.460870,12.070652,6.033403,6.347014,6.512159,6.093082,6.504460,6.743331
1,18,34,9786383567,Male,Subgroup P,0,1,3.99,7,81435.0,...,13.380953,11.141304,11.520652,11.871739,6.033403,6.347014,6.512159,6.093082,6.504460,6.743331
2,15,36,5602306401,Male,Subgroup P,0,1,3.05,1,86400.0,...,15.597403,10.393478,10.777174,11.659783,6.064177,6.380910,6.548825,6.117186,6.522880,6.771772
3,36,41,8107765424,Male,Subgroup P,0,1,20.29,1,79176.0,...,12.290043,11.039130,11.023913,11.963043,6.069724,6.365864,6.512409,6.091926,6.469195,6.700504
4,49,51,7879842771,Male,Subgroup P,0,1,13.66,7,94511.0,...,12.290043,10.760870,11.308696,12.006522,6.069724,6.365864,6.512409,6.091926,6.469195,6.700504

In [12]:
df_P = pd.DataFrame(df[df['Subgroup'] == 'Subgroup P'])
df_P.head()

,ADI,Age,person_id,Gender,Subgroup,absence_indicator,analytic_period_id,tenure,overtime,salary,...,extreme_heat_ssp585_2045,wildfire_potential_2018,wildfire_potential_2019,wildfire_potential_2019.1,wildfire_potential_ssp245_2025,wildfire_potential_ssp245_2035,wildfire_potential_ssp245_2045,wildfire_potential_ssp585_2025,wildfire_potential_ssp585_2035,wildfire_potential_ssp585_2045
0,28,37,3030515063,Male,Subgroup P,0,1,18.25,1,115700.0,...,13.380953,10.975000,11.460870,12.070652,6.033403,6.347014,6.512159,6.093082,6.504460,6.743331
1,18,34,9786383567,Male,Subgroup P,0,1,3.99,7,81435.0,...,13.380953,11.141304,11.520652,11.871739,6.033403,6.347014,6.512159,6.093082,6.504460,6.743331
2,15,36,5602306401,Male,Subgroup P,0,1,3.05,1,86400.0,...,15.597403,10.393478,10.777174,11.659783,6.064177,6.380910,6.548825,6.117186,6.522880,6.771772
3,36,41,8107765424,Male,Subgroup P,0,1,20.29,1,79176.0,...,12.290043,11.039130,11.023913,11.963043,6.069724,6.365864,6.512409,6.091926,6.469195,6.700504
4,49,51,7879842771,Male,Subgroup P,0,1,13.66,7,94511.0,...,12.290043,10.760870,11.308696,12.006522,6.069724,6.365864,6.512409,6.091926,6.469195,6.700504

In [13]:
df_P.shape

(19623, 74)

In [15]:
# Data Cleaning

df_wrong_days = df_P.loc[df_P['absence_indicator'] > 365]
df_P = df_P.drop(df_wrong_days.index)

df_P.shape

(19623, 74)

In [16]:
df_P.info()

<class 'pandas.core.frame.DataFrame'>
Index: 19623 entries, 0 to 39616
Data columns (total 74 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   ADI                                 19623 non-null  int64
 1   Age                                 19623 non-null  int64
 2   person_id                           19623 non-null  int64
 3   Gender                              19623 non-null  object
 4   Subgroup                            19623 non-null  object
 5   absence_indicator                   19623 non-null  int64
 6   analytic_period_id                  19623 non-null  int64
 7   tenure                              19623 non-null  float64
 8   overtime                            19623 non-null  int64
 9   salary                              19623 non-null  float64
 10  performance_rating                  19623 non-null  int64
 11  BiometricScreeningParticipants      19623 non-null  int64
 12  HRQParticipants                     19623 non-null  int64
 13  lsbio_cholesterol                   19623 non-null  int64
 14  lsbio_glucose                       19623 non-null  int64
 15  lsbio_bp                            19623 non-null  int64
 16  lsbio_weight                        19623 non-null  int64
 17  lsbio_trig                          19623 non-null  int64
 18  lshrq_physact                       19623 non-null  int64
 19  lshrq_tobacco                       19623 non-null  int64
 20  lshrq_nutrition                     19623 non-null  int64
 21  lshrq_stress                        19623 non-null  int64
 22  lshrq_genHealth                     19623 non-null  int64
 23  lshrq_wellbeing                     19623 non-null  int64
 24  lshrq_alcohol                       19623 non-null  int64
 25  lshrq_sleeping                      19623 non-null  int64
 26  cc_RespiratorySinusAllergy_chronic  19623 non-null  int64
 27  cc_diabetes                         19623 non-null  int64
 28  cc_cancer                           19623 non-null  int64
 29  cc_mskChronic                       19623 non-null  int64
 30  cc_cholesterol                      19623 non-null  int64
 31  cc_cardiac                          19623 non-null  int64
 32  cc_depression                       19623 non-null  int64
 33  cc_obesity                          19623 non-null  int64
 34  cc_mskAllOther                      19623 non-null  int64
 35  cc_behavioralAllOther               19623 non-null  int64
 36  cc_ckd                              19623 non-null  int64
 37  concurrent_risk                     19623 non-null  float64
 38  rx_nonClaimant                      19623 non-null  int64
 39  rx_nonCompliant                     19623 non-null  int64
 40  prog_1                              19623 non-null  int64
 41  prog_2                              19623 non-null  int64
 42  prog_3                              19623 non-null  int64
 43  prog_4                              19623 non-null  int64
 44  prog_5                              19623 non-null  int64
 45  prog_6                              19623 non-null  int64
 46  prog_7                              19623 non-null  int64
 47  prog_8                              19623 non-null  int64
 48  prog_9                              19623 non-null  int64
 49  prog_10                             19623 non-null  int64
 50  prog_11                             19623 non-null  int64
 51  prog_12                             19623 non-null  int64
 52  prog_13                             19623 non-null  int64
 53  prog_14                             19623 non-null  int64
 54  prog_15                             19623 non-null  int64
 55  prog_16                             19623 non-null  int64
 56  extreme_heat_2018                   19623 non-null  int64
 57  extreme_heat_2019                   19623 non-null  int64
 58  extreme_heat_2020                   19623 non-null  int64
 59  extreme_heat_ssp245_2025            19623 non-null  float64
 60  extreme_heat_ssp245_2035            19623 non-null  float64
 61  extreme_heat_ssp245_2045            19623 non-null  float64
 62  extreme_heat_ssp585_2025            19623 non-null  float64
 63  extreme_heat_ssp585_2035            19623 non-null  float64
 64  extreme_heat_ssp585_2045            19623 non-null  float64
 65  wildfire_potential_2018             19623 non-null  float64
 66  wildfire_potential_2019             19623 non-null  float64
 67  wildfire_potential_2019.1           19623 non-null  float64
 68  wildfire_potential_ssp245_2025      19623 non-null  float64
 69  wildfire_potential_ssp245_2035      19623 non-null  float64
 70  wildfire_potential_ssp245_2045      19623 non-null  float64
 71  wildfire_potential_ssp585_2025      19623 non-null  float64
 72  wildfire_potential_ssp585_2035      19623 non-null  float64
 73  wildfire_potential_ssp585_2045      19623 non-null  float64
dtypes: float64(18), int64(54), object(2)
memory usage: 11.2+ MB

In [17]:
health_factors = ['ADI', 'Age', 'Gender', 'lsbio_cholesterol', 'lsbio_glucose', 'lsbio_bp', 'lsbio_weight', 'lsbio_trig', 
                  'lshrq_physact', 'lshrq_tobacco', 'lshrq_nutrition', 'lshrq_stress', 'lshrq_genHealth', 'lshrq_wellbeing', 'lshrq_alcohol', 'lshrq_sleeping', 
                  'cc_RespiratorySinusAllergy_chronic', 'cc_diabetes', 'cc_cancer', 'cc_mskChronic', 'cc_cholesterol', 'cc_cardiac', 'cc_depression', 'cc_obesity', 
                  'cc_mskAllOther', 'cc_behavioralAllOther', 'cc_ckd', 'concurrent_risk', 'rx_nonClaimant', 'rx_nonCompliant']

categorical_variables = ['Gender', 'lsbio_cholesterol', 'lsbio_glucose', 'lsbio_bp', 'lsbio_weight', 'lsbio_trig', 
                         'lshrq_physact', 'lshrq_tobacco', 'lshrq_nutrition', 'lshrq_stress', 'lshrq_genHealth', 'lshrq_wellbeing', 'lshrq_alcohol', 'lshrq_sleeping', 
                         'cc_RespiratorySinusAllergy_chronic', 'cc_diabetes', 'cc_cancer', 'cc_mskChronic', 'cc_cholesterol', 'cc_cardiac', 'cc_depression', 'cc_obesity', 
                         'cc_mskAllOther', 'cc_behavioralAllOther', 'cc_ckd', 'concurrent_risk', 'rx_nonClaimant', 'rx_nonCompliant']

In [ ]:
# y variable = absence_indicator
# x variables = health_factors